jupyter-lsp/jupyterlab-lsp

- package.json
- src/adapters/codemirror.ts
- src/adapters/file_editor.ts
- src/adapters/jupyterlab.ts
- src/adapters/notebook.ts
- src/completion.ts
- src/extractors/regexp.spec.ts
- src/extractors/regexp.ts
- src/extractors/types.ts
- src/magics/defaults.spec.ts
- src/magics/defaults.ts
- src/magics/maps.ts
- src/positioning.ts
- src/utils.ts
- src/virtual/document.spec.ts
- src/virtual/document.ts
- src/virtual/editor.spec.ts
- src/virtual/editor.ts
- src/virtual/editors/file_editor.ts
- src/virtual/editors/notebook.ts
Correctly implements LSP for `%%time`, `%%python` and `%%R` cell magics; allows for the LSP use in nested code for any kernel, providing simple extractor interface to define patterns in the source which should be treated as a foreign language.
Related groundwork, which was backwards compatible, is already in master:
- Add virtual document abstraction: 75fd1b396b7d49071ed425b0dace827c131e2f8e
- Documentation: eb79664ad46ca063dfbdd73d0185cedca072a393, 6282f23b097b5edd3e61b224fc2bcf87c7f9f560, 
- Implement foreign documents connections: bd643b487a4efb8f26c2609b72f4519e869f0820
> Nested virtual documents

- src/adapters/codemirror/feature.ts
- src/adapters/codemirror/features/rename.ts
- src/adapters/jupyterlab/jl_adapter.ts
- src/connection.ts
- src/virtual/document.ts
General notes:
- It only works when using absolute paths and not for synced documents (e.g. rope in pyls seems to require the file to exists):
- we may need to mirror the virtual documents in the file system to allow for seamless integration of rename action. Those files could be hidden; however, there are OS-compatibility, safety and import systems (varying across languages) concerns with such a solution;
- notebooks are not supported for now as those would require the virtual documents to be saved on the disk (e.g. as hidden files)
TODO:
This PR does **not** implement workspace-wide edits (rename action fails if multiple files need to be edited). A shared mechanism for opening files in background is needed for this as well as for #41.
> Add "rename" action

- MANIFEST.in
- environment.yml
- py_src/jupyter_lsp/CONTRIBUTING.md
- py_src/jupyter_lsp/jsonrpc.py
- py_src/jupyter_lsp/serverextension.py
- py_src/jupyter_lsp/session.py
- py_src/jupyter_lsp/specs/__init__.py
- py_src/jupyter_lsp/specs/helpers/languageserver.R
- py_src/jupyter_lsp/specs/languageserver.R
- py_src/jupyter_lsp/specs/r_languageserver.py
- py_src/jupyter_lsp/specs/utils.py
- py_src/jupyter_lsp/tests/conftest.py
- setup.py
- src/adapters/jupyterlab/file_editor.ts
- src/adapters/jupyterlab/jl_adapter.ts
Builds on the upstream, apparently works. [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-lsp/full_conda?urlpath=lab) is solid.
Also applied the python formatters, etc. And, because `r-lintr` was working, I even linted the helper script, without even knowing r! Hooray dogfood!
As I was perusing upstream, i see that `r-languageserver` also supports rmarkdown. Definitely a nice value proposition, but apparently codemirror isn't telling anybody, so it comes back `plain`. 
I'm not sure what ordering of things made a difference but it just started working against my local dev env (also linux on conda).
Let's squash merge this, if we get it working!
> More work on R/conda/binder

- src/adapters/codemirror/features/diagnostics.ts
- src/adapters/codemirror/testutils.ts
- src/adapters/jupyterlab/file_editor.ts
- src/adapters/jupyterlab/jl_adapter.ts
- src/adapters/jupyterlab/notebook.ts
- src/connection_manager.ts
- src/virtual/editor.spec.ts
- src/virtual/editor.ts
- src/virtual/editors/file_editor.ts
- src/virtual/editors/notebook.ts
This also fixes init problems #39
> Reload connections after kernel or file name change

- atest/01_Editor.robot
- atest/Keywords.robot
- atest/Ports.py
- atest/Variables.robot
Been noticing some flake on #67, #66: sorry to make so many :x: .
I'd say if this passes, it can be merged... it will be an on-going battle to keep the browser tests happy.
> Robot flake fixes 🤖❄️ 

- README.md
- py_src/jupyter_lsp/CONTRIBUTING.md
- py_src/jupyter_lsp/README.md
- py_src/jupyter_lsp/types.py
- requirements-atest.txt
- requirements-dev.txt
- requirements-lab.txt
- requirements-utest.txt
- requirements.txt
- setup.cfg
For #70.
This removes the `jupyterlab` dependency, leaving `notebook` (and adding the missing `setuptools`). Lab will still get installed when following the dev instructions (which I've also revisited a bit).
> Remove hard lab dependency

- atest/00_Smoke.robot
- schema/plugin.json
Even though we don't have any settings to configure, we need an empty `properties` so that the settings editor can draw it without failing (and mucking up the UI).
Will also add a test...
> Add an empty properties to settings schema

- azure-pipelines.yml
- py_src/jupyter_lsp/_version.py
Adds trailing `0` to the python version specs.
The PEP 440 [pre-release spec](https://www.python.org/dev/peps/pep-0440/#pre-releases) looks like
```
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release
```
> use PEP 440 version specs

- py_src/jupyter_lsp/handlers.py
- py_src/jupyter_lsp/schema/__init__.py
- py_src/jupyter_lsp/schema/servers.schema.json
- py_src/jupyter_lsp/serverextension.py
- py_src/jupyter_lsp/session.py
- py_src/jupyter_lsp/tests/conftest.py
- py_src/jupyter_lsp/tests/test_session.py
- py_src/jupyter_lsp/types.py
For https://github.com/krassowski/jupyterlab-lsp/pull/78#issuecomment-546907659
This adds a REST-ish (whatever) JSON endpoint for getting the current state of the server sessions at `/lsp` (no trailing slash).
<details>
<summary>example response</summary>
<pre>
{
"version": 0,
"sessions": [
{
"languages": [
"bash",
"sh"
],
"handler_count": 0,
"status": "not_started",
"last_server_message_at": null,
"last_handler_message_at": null
},
{
"languages": [
"css",
"less",
"scss"
],
"handler_count": 0,
"status": "not_started",
"last_server_message_at": null,
"last_handler_message_at": null
},
{
"languages": [
"dockerfile"
],
"handler_count": 0,
"status": "not_started",
"last_server_message_at": null,
"last_handler_message_at": null
},
{
"languages": [
"html"
],
"handler_count": 0,
"status": …
> Add server status endpoint

- package.json
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/index.ts
- packages/jupyterlab-lsp/src/virtual/editors/notebook.ts
- yarn.lock
This allows us to:
- remove some dependencies, especially conflicting CodeMirror versions
- remove lots of unused code, since we got the adapter part rewritten
- start customizing the connection behavior to our liking
Here is the link to the repo: https://github.com/krassowski/lsp-ws-connection. We may want to pull this in as a package, though there is a slight difference in the license (ISC), so not sure about this.
I also removed `jsonrpc-ws-proxy` - high time to have the transition finished off.
> Migrate from lsp-editor-adapter to (stripped) lsp-ws-connection.

- README.md
- RELEASE.md
- azure-pipelines.yml
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
Let's see if I found all the places with the version number.
> Release 0.6.1, update RELEASE.md

- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/utils.ts
- py_src/jupyter_lsp/handlers.py
- py_src/jupyter_lsp/paths.py
- py_src/jupyter_lsp/serverextension.py
- py_src/jupyter_lsp/tests/test_paths.py
For #91.
This is a lightweight approach which adds a (hopefully) canonical `rootUri` to `page_config`, where it probably belongs in the first place, rather than putting it on something language server specific. This simplifies a lot of behavior... we shall see (especially r on windows)!
> Add rootUri to PageConfig

- CHANGELOG.md
- CONTRIBUTING.md
- EXTENDING.md
- README.md
- azure-pipelines.yml
- environment.yml
- packages/jupyterlab-lsp/src/connection_manager.ts
- py_src/jupyter_lsp/__init__.py
- py_src/jupyter_lsp/constants.py
- py_src/jupyter_lsp/handlers.py
- py_src/jupyter_lsp/manager.py
- py_src/jupyter_lsp/session.py
- py_src/jupyter_lsp/specs/utils.py
- py_src/jupyter_lsp/tests/conftest.py
- py_src/jupyter_lsp/tests/listener.py
- py_src/jupyter_lsp/tests/test_listener.py
- py_src/jupyter_lsp/tests/test_session.py
- py_src/jupyter_lsp/trait_types.py
- py_src/jupyter_lsp/types.py
- requirements.txt
- scripts/atest.py
- setup.cfg
This adds a listener API, mostly following #99.
Definitely need to chew on this a bit more, but wanted to get it out there once it (apparently) started working. ~~For example, there's a lot of duplicated code for the two types of listeners... there could be a single decorator with a `sender="session"`, with a default of listening to _all_ messages, which would have its advantages, I suppose. I _don't_ anticipate actually adding any listeners on this PR, or at least not any that would run by default.~~
Fixes #102.
> Add message listener API

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/intent_to_implement.md
- .github/ISSUE_TEMPLATE/language_server_builtin.md
- .github/ISSUE_TEMPLATE/language_server_byo.md
- .github/pull_request_template.md
Just to get the ball rolling... 
#96
N/A
Contributors/end users will see a little more UI when making PRs/Issues: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
N/A
> Add GitHub templates

- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
- packages/jupyterlab-lsp/style/statusbar.css
Implement mockup from #78. Still, a lot to be done, but a lot of improvement compared to the previous statusbar.
#78
Temporarily added hardcoded interfaces for server specs (until #98 is here).
None
> Statusbar with server status

- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
- #106 looks great, but react complains a lot about some list stuff  
None (well, they might get a bit less of a show when checking the console for errors, I suppose)
None
> add keys to list-like things to squash react console errors

- py_src/jupyter_lsp/types.py
- #111 
Wraps the user-provided listener call in a try/catch block with some logging (message content, traceback).
Failing listeners should not break delivery of messages to client.
None
> Capture listener exceptions, avoid expecting method

- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
- packages/jupyterlab-lsp/style/statusbar.css
Mentioned in #115 
None
Before:
After:
Before:
After:
None
> Prevent wrapping of server headers and the statusbar item

- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/rename.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/command_manager.ts
- packages/jupyterlab-lsp/src/virtual/editors/notebook.ts
Implement a UX workaround for rope/pyls rename issue for the case of syntax errors in the source code.
In #115 an issue with rename for Python (when using pyls) was identified:
rename was failing with an obscure message when the source code could not be parsed correctly by rope (due to a user's syntax error).
This workaround detects such a condition using diagnostics feature provides a nice error message to the user (UX first).
#115
`ICommandContext` now includes `VirtualEditor`. `Diagnostics` feature got a new, public database of diagnostics (`diagnostics_db: IEditorDiagnostic[]`) which will be also used to implement the diagnostics Panel widget (#42).
Note: the error is in the 4th cell (1-based indexing) because above the code cells there are two markdown cells; we could change the code …
> Implement a UX workaround for rope/pyls rename issue

- CHANGELOG.md
- packages/jupyterlab-lsp/src/adapters/codemirror/feature.spec.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/feature.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.spec.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics_listing.tsx
- packages/jupyterlab-lsp/src/adapters/codemirror/features/highlights.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/rename.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/testutils.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/command_manager.ts
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
- packages/jupyterlab-lsp/src/virtual/editor.spec.ts
- packages/jupyterlab-lsp/style/diagnostics_listing.css
Add diagnostics/inspections panel.
Closes #42 
- adds jest test for inspections in a notebook
- adds a few testutilis, moves utilities to testutilis from feature.spec.ts
- fixes a bug with foreign governments not being updated TODO tests
- fixes diagnostics being displayed in a wrong document
- protects from failures in highlights feature (such is a while other story and requires a lot of testing)
Adds a diagnostics panel. The diagnostics table is scrollable, sortable and a click on the diagnostic moves the user to the relevant place in the notebook or editor.
None
> Diagnostics panel

- CHANGELOG.md
- azure-pipelines.yml
- packages/jupyterlab-lsp/package.json
Follows #132. A link to an outdated commit was removed from the changelog, no other changes.
> Release jupyterlab-lsp 0.7.0-beta1

- CHANGELOG.md
- atest/01_Editor.robot
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/command_manager.spec.ts
- packages/jupyterlab-lsp/src/command_manager.ts
- packages/jupyterlab-lsp/src/index.ts
- packages/jupyterlab-lsp/src/virtual/editors/notebook.ts
Commands are now also accessible from the command palette, while diagnostics panel is tested during diagnostics tests.
A prerequisite for a test and fix for #141.
`ContextMenuCommandManager` became `ContextCommandManager` and takes care of attachment, visibility and execution of commands invoked from both the context menu and commands palette. 
One can discover options of the extension via the command palette.
`ContextCommandManager` and its constructor.
> Add commands to palette, add diagnostics panel tests

- CHANGELOG.md
- atest/01_Editor.robot
- atest/03_Notebook.robot
- atest/Keywords.robot
- atest/Variables.robot
- atest/examples/Foreign extractors.ipynb
- atest/examples/Python.ipynb
- packages/jupyterlab-lsp/src/extractors/defaults.ts
Fix R foreign extractor, add bash alias, add notebook and extractors acceptance tests.
Added `03_Notebook.robot`, generalized some keywords relevant to both file editor and notebook and moved them to `Keywords.robot`.
Foreign code extractors for `%%bash` and `%%R` cells work now and again (respectively) :tada:
> Fix R foreign extractor, add bash alias, add tests

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/Completion.ipynb
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/completion.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/notebook.ts
- packages/jupyterlab-lsp/src/virtual/editor.ts
Fixes a previously unreported bug which prevented completions from working when kernel was shut down, and removes a spurious console error log. 
A pre-requisite for #143.
I tried to test auto-invocation of completer (using a trigger character of dot) but while it works perfectly in my browsers, the selenium seems to have a problem with the amount / frequency of async and semaphore operations I used to synchronize CodeMirror and VirtualDocument changes.
My failed attempt was:
```robot
Triggers Completer On Dot
Setup Notebook    Python    Completion.ipynb
Enter Cell Editor    2    line=1
Press Keys    None    .
Wait Until Keyword Succeeds  10x   0.5s   Cell Editor Should Equal  2   list.
Sleep   2s
Wait Until Page Contains Element    ${COMPLETER_BOX}    timeout=10s   
Completer Should …
```
> Add initial tests for completion feature

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/Completion.ipynb
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/completion.ts
There has two changes.
All in `completion.ts`.
1.  change `merge_replies` function.
when `lsp.start > kernel.start`, correct the right prefix. 
`kernel.start` is the wrong index, because this index is merge all content in cell, and calculate the index, not the current line index.
2.  change `hint` function.
if check text startsWith token case sensitive,
It will keep a no need token value.
Input `from time import T`
before after completion, there will be `from time import Ttime`
now, there will be `from time import time`
> completion case sensitive will  keep a no need token value

- CHANGELOG.md
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/completion.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/lsp-ws-connection/src/ws-connection.ts
Implements didSave which solves #95 (as far as our responsibility goes, making it work without saving is on the LSP server).
None
> Implement didSave, fixes #95

- CHANGELOG.md
- CONTRIBUTING.md
- atest/05_Features/Completion.robot
- atest/05_Features/Signature.robot
- atest/Keywords.robot
- atest/Variables.robot
- atest/examples/Signature.ipynb
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/adapters/codemirror/cm_adapter.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/completion.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/signature.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/virtual/console.ts
- packages/jupyterlab-lsp/src/virtual/editor.ts
- packages/jupyterlab-lsp/style/console.css
- packages/lsp-ws-connection/src/ws-connection.ts
change `ws-connection.ts`, `getSignatureHelp` function.
In ipynb with python3, `location.ch`, will get wrong character.
So, use `location.ch-1` to fix the character right
> fix ws signature failed

- README.md
- atest/00_Smoke.robot
- atest/Keywords.robot
- ci/job.combine.yml
- ci/job.test.yml
- environment.yml
- requirements-lab.txt
- scripts/atest.py
- scripts/combine.py
- scripts/utest.py
- https://github.com/krassowski/jupyterlab-lsp/pull/146#issuecomment-573379944
- adds 3.8 excursions
- https://github.com/krassowski/jupyterlab-lsp/pull/145#issuecomment-572315068
- only retries failed tests
None
None
> More Robot Test Robustness

- CHANGELOG.md
- packages/jupyterlab-lsp/src/extractors/defaults.spec.ts
- packages/jupyterlab-lsp/src/extractors/defaults.ts
- packages/jupyterlab-lsp/src/magics/rpy2.ts
Follows #144 with a fix for a case when `%R` line magic is used to import / export stuff but does not introduce any code to the R document, e.g. `%R -i data`.
In addition, the dummy assignments to introduce the imported varaibles are now all in one line with the line code; this might improve diagnostics until a better solution is in place.
None
None
> Fix the (hopefully) last corner case of %R line magic

- CHANGELOG.md
- atest/01_Editor.robot
- atest/04_Interface/DiagnosticsPanel.robot
- atest/Keywords.robot
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics_listing.tsx
- yarn.lock
Allows choosing which columns to display/hide in the diagnostic panel, using a context menu action.
Closes #149 
Greatly simplifies the `DiagnosticListing.render()` function body by moving the column-specific code to a newly created `Column` class (not exported).  A new interface `IListingContext` facilitates this transition.
None.
> Allow to hide chosen columns in diagnostics panel

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/Keywords.robot
- atest/examples/Completion.ipynb
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/completion.ts
Fixes the completer issues as detailed in #30, adding many test cases.
Bugfixes only. New useful robot keywords:
- `Place Cursor In Cell Editor At` (global, in addition to entering a specific cell and line allows to set cursor after a specific character), and
- `Select Completer Suggestion` (Completer)
Well, the completer is now (fully?) reliable ;)
None
> Fix various bugs in the completer feature

- CHANGELOG.md
- atest/05_Features/Signature.robot
- packages/jupyterlab-lsp/src/adapters/codemirror/features/signature.ts
Fixes #161
Sadly no browser test for this yet. My faild attempt was:
```robot
Signature Displays Markdown Documentation
Setup Notebook    Python        Signature.ipynb
Enter Cell Editor    3    line=2
Wait Until Fully Initialized
Press Keys    None    (
Wait Until Keyword Succeeds    20x    0.5s    Page Should Contain Element    ${SIGNATURE_BOX}
Element Should Contain    ${SIGNATURE_BOX}    Functions to construct, coerce and check for both kinds of R lists.
Element Should Contain    ${SIGNATURE_BOX} strong    R
[Teardown]    Clean Up After Working With File    Signature.ipynb
```
Where cell 3rd was:
```
%%R
line
```
but I got stuck on `Wait Until Fully Initialized`  - some problems with the R languageserver (strangely, only during tests...)
None
> Correctly display documentation of signature returned as MarkupContent

- CHANGELOG.md
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/command_manager.ts
Fixes #157 
Added `adapter` to the command context, but kept the widget private to keep the code from getting more inter-dependent.
Diagnostics panel open at the bottom, by splitting the active widget in half. 
None
> Start the diagnostics panel docked at the bottom

- ci/job.test.yml
> Bump Azure CI to run on macOS-10.14 (was .13)

- CHANGELOG.md
- ci/job.docs.yml
- package.json
- packages/jupyterlab-lsp/src/adapters/jupyterlab/file_editor.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/notebook.ts
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/connection_manager.ts
- requirements/docs.yml
- yarn.lock
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-lsp/fix-docker-diagnostics?urlpath=lab%2Ftree%2Fatest%2Fexamples%2FDockerfile)
- fixes #201
N/A
> sendOpen after connection handlers are installed

- README.md
Its no longer needed, and severely annoying when combining with pipenv (as this enables pre mode for the whole project , which can and will break other things.)
I brutally scrapped the whole template for how to contribute a patch and I think I'll let the diff speak for itself 😂. Loving the project and I'm eagerly watching the changes happening, great job so far 👍.
> Remove --pre from pip install instructons

- CHANGELOG.md
- README.md
> Release v1.0.0 (compatible with JupyterLab 2.0)

- atest/03_Notebook.robot
- extracted from #231
make lintr whitespace message check less specific
none
none
> make lintr whitespace message check less specific

- packages/jupyterlab-lsp/style/index.css
Fixes #195. I gave up on having a different style for fuzzy matches - it does not seem to be something that others editors do, and there is no reasonable support from the servers for the distinction between fuzzy and exact highlight.
As this still uses the same colour as is used for line highlights, I added a small dotted outline when in the active line.
When using the dark theme, the fuzzy highlights (as returned by R language server) are now readable and indistinguishable from normal highlights:
There is a very subtle outline added for active line:
Same with the light theme:
None
> Don't use hardcoded color for fuzzy highlight, show outline when in active line

- README.md
- binder/environment.yml
- ci/job.docs.yml
- ci/job.lint.yml
- ci/job.test.yml
- requirements/lab.txt
Change JLab constrain to >=2.0, <3.0.0a0 in test scripts.
Consequence of #242 as discussed in https://github.com/conda-forge/staged-recipes/pull/11280#discussion_r407234128
N/A
N/A
N/A
> Allow jlab version lesser than 3.0.0a0

- ci/env-test.yml.in
- ci/job.lint.yml
- requirements/atest.txt
- requirements/atest.yml
- requirements/lint.yml
- fixes #262 
robotframework 3.2 changed a number of interfaces: we'll likely want to use it, but for now, let's pin.
n/a
n/a
> Pin robotframework to <3.2

- binder/environment.yml
- requirements/lint.yml
#290 shows a failure in the lint step (all the actual tests pass ok). The root cause seems to be a recent release of isort (5.0) which affects nblint and pylint. Until both have migrated to isort 5.0 the proposed solution is to pin isort <5.
Upstream/root issues:
```python
robot --name Linux37 --outputdir /home/vsts/work/1/s/atest/output/dry_run_linux_37_1 --output /home/vsts/work/1/s/atest/output/dry_run_linux_37_1.robot.xml --log /home/vsts/work/1/s/atest/output/dry_run_linux_37_1.log.html --report /home/vsts/work/1/s/atest/output/dry_run_linux_37_1.report.html --xunitskipnoncritical --xunit /home/vsts/work/1/s/atest/output/dry_run_linux_37_1.xunit.xml --variable OS:Linux --variable PY:37 --randomize all --dryrun --console quiet --noncritical language:yamlANDfeature:config --noncritical …
```
> Pin isort to restore the lint step in CI

- CHANGELOG.md
- packages/jupyterlab-lsp/src/magics/defaults.spec.ts
- packages/jupyterlab-lsp/src/magics/defaults.ts
Partially fixes too aggressive line magic (%) and shell (!) substitution which was pyflakes causing issues.
Fixes #281.
Regular expressions got improved, tests added.
Pyflakes should more often work than not. Not always as some things cannot be achieved with regular expressions.
None
> Alleviate too aggressive line magics substitution #281

- CHANGELOG.md
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
Fixes #254
None
The link to servers will now work
None
> Update location of Language Servers information

- py_src/jupyter_lsp/tests/test_paths.py
Attempts to address https://github.com/krassowski/jupyterlab-lsp/pull/301#issuecomment-665735786, which can be also seen in #304
> Fix tests/mypy error for "not WIN" condition

- CONTRIBUTING.md
- atest/Keywords.robot
- py_src/jupyter_lsp/tests/conftest.py
- py_src/jupyter_lsp/tests/test_bad_spec.py
- py_src/jupyter_lsp/tests/test_listener.py
- scripts/atest.py
- yarn.lock
- fixes #308
- newest `geckodriver` performs an (actually quite helpful, i guess) check whether `firefox_binary` is _in fact_ a firefox binary
- our test environment in CI uses firefoxen delivered by conda-forge, which use wrapper scripts
- n/a
- n/a
> add env var for firefox, fallback to known locations or which

- CHANGELOG.md
- atest/04_Interface/Statusbar.robot
- atest/Keywords.robot
- atest/examples/example.plain
- packages/jupyterlab-lsp/src/components/statusbar.tsx
It turns out that the `detected_documents` were basically all documents (documents across all open editors) rather than documents detected in given editor (as expected) probably introduced during refactor towards connection manager, but will be fine now as I added a test for it (with two editors being open).
This is a further fix to #310 (after https://github.com/krassowski/jupyterlab-lsp/pull/318/commits/4e5b2adf655120458cc8be4b453fe9a78c98e061 which made a progress towards it before).
I reduced the verbosity of the status message from previously committed "Initialized (additional servers can be installed)" to "Initialized (additional servers needed)".
None
> Fix statusbar message pooling data from all editors

- CHANGELOG.md
- atest/04_Interface/DiagnosticsPanel.robot
- atest/05_Features/Completion.robot
- atest/Keywords.robot
- atest/Variables.robot
- atest/examples/Diagnostic.ipynb
- atest/examples/Panel.ipynb
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
Together with prematurely pushed to master 75a90e84567bb177a8a5a641235811ddf831aa5f, closes #154 and probably helps #160.
> Diagnostics panel improvements: copy, ignore (filter), jump from context menu

- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/lsp.ts
Works around #334 (proposed solution 2, to stay until (1) can be implemented)
None
> Implement a workaround for #334

- CHANGELOG.md
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.ts
See the test cases added for details. Final fix for this week, hopefully nothing else will break LSP in my notebooks :)
> Fix too aggressive overrides of IPython's pinfo (`?`) and pinfo2 (`??`)

- CHANGELOG.md
- packages/jupyterlab-lsp/src/features/syntax_highlighting.ts
Fixes #360
Added an if to chek current mode.
Great performance increase if working with `%%language` magics.
None
> Fix performance issues caused by lazy syntax highlight implementation

- CHANGELOG.md
- atest/05_Features/Syntax_highlighting.robot
- packages/jupyterlab-lsp/src/features/syntax_highlighting.ts
Fixes #379.
Keep track of editors where custom syntax mode is applied and revert to the default when no longer deemed appropriate to apply the custom mode.
None
> Fix syntax highlighting not being deactivated

- CHANGELOG.md
- packages/jupyterlab-lsp/src/editor_integration/codemirror.ts
Fixes #380
Fixes some premature optimization done poorly, minimal change set and no tests as attempts at testing clipboard with Robot wasted me some precious ours the other week.
None
> Correctly extract last character on paste

- CHANGELOG.md
- atest/05_Features/Completion.robot
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
Fixes #388
Added a test for continuous hinting, but does not test the bug itself (need some better way to test that an action does NOT happen).
None
- [.] tested
> Fix continuous hinting showing up when it has nothing to offer

- packages/jupyterlab-lsp/src/adapter_manager.ts
- packages/jupyterlab-lsp/src/index.ts
Issue: https://github.com/krassowski/jupyterlab-lsp/issues/398
Registering Context Commands Manager with already added types.
None
Backword compatible.
> Register Context Commands with already added types

- packages/jupyterlab-lsp/src/index.ts
Export tokens for other extensions to depend on them.
If tokens are not exported, one can retrieve them doing *e.g.*:
```Typescript
import { ILSPAdapterManager } from '@krassowski/jupyterlab-lsp/lib/tokens';
```
But this code will be compiled by webpack into
```javascript
/* harmony import */ var _krassowski_jupyterlab_lsp_lib_tokens__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @krassowski/jupyterlab-lsp/lib/tokens */ "./node_modules/@krassowski/jupyterlab-lsp/lib/tokens.js");
```
Meaning that the third-party extension now ships its own copy of `@krassowski/jupyterlab-lsp`, with its own definition of the Tokens.
If we export the tokens, third-party extensions are able to do:
```Typescript
import { ILSPAdapterManager } from '@krassowski/jupyterlab-lsp';
```
Which compiles to: …
> Export tokens

- CHANGELOG.md
- docs/Configuring.ipynb
- py_src/jupyter_lsp/manager.py
- py_src/jupyter_lsp/serverextension.py
- py_src/jupyter_lsp/tests/test_extension.py
Fixes #353
Move the ".virtual_documents" definition to a configuration in `LanguageServerManager`. Its default value is kept
but that default value can be overwritten by the environment variable `JP_LSP_VIRTUAL_DIR`
None - except if they must know about the virtual document folder.
None
> virtual_documents customization

- packages/jupyterlab-lsp/src/connection_manager.ts
When there is no language server installed, it fails with
```
TypeError: Path must be a string. Received null
```
Which is not very easy to understand without looking into the code. This PR makes it fail with a nicer error message that tells what is wrong.
> Improve error message when there is no language server installed for the current language

- CHANGELOG.md
- atest/03_Notebook.robot
- atest/Keywords.robot
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/adapters/notebook/notebook.ts
- packages/jupyterlab-lsp/src/editor_integration/testutils.ts
- packages/jupyterlab-lsp/src/virtual/codemirror_editor.ts
Previously the binding of events was only performed upon the user entering a code cell. Moreover, updates to the virtual document were only triggered on code edition, and not on cell edition (rearrangement, cell pasting etc). This was kind-of ok for the initial demo, but a number of scenarios require a better management of the events binding  [E] and document updates [D]:
- code cell being converted to markdown or raw cell:
- [E] we do not want to trigger LSP there
- [D] we want to refresh virtual document to exclude the converted fragment
- code cells being pasted or converted from markdown/raw cells:
- [E] user should be able to get context menu on those without the need to enter them first
- [D] the diagnostics should be shown in these just after paste
- cells being moved around:
- [D] …
> Refactor how the notebook changes are picked up, events bound and unbound

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- py_src/jupyter_lsp/_version.py
> Release v2.1.0

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/schema/jump_to.json
- packages/metapackage/package.json
It seems that the nice Mac Command character (⌘) was breaking JupyterLab extension system because of poor handling of encoding. Probably not worth fixing in lab because of the new extension system so just removing the offending character.
Hopefully fixes #428.
> Hotfix crash "blank screen" likely related to Mac command character

- atest/Keywords.robot
- binder/environment.yml
- docs/Configuring.ipynb
- py_src/jupyter_lsp/manager.py
- py_src/jupyter_lsp/non_blocking.py
- py_src/jupyter_lsp/types.py
- requirements/atest.yml
- requirements/docs.yml
- requirements/github-actions.yml
- requirements/lint.yml
- scripts/bump_versions.py
- scripts/integrity.py
- scripts/lint.py
- scripts/nblint.py
- setup.cfg
Sorry this kinda ended up as a mess (should have been a one-character PR, ha), but i had to rebuild my env, and some things were going a bit wacky. This has me running all the way to failing some acceptance tests for other reasons, but figured it was worth getting out, if only for cherry-picking the good parts.
- fixes #444
- fix robot parsing of JSON which might contain single `\` escapes
- upgrade isort
- pin jedi
- get isort and and all the fixings from `conda-forge` only with `nodefaults` instead of `defaults`
n/a
n/a
> [wip] Fix robot PageConfig parsing, upgrading isort, pin jedi

- .github/workflows/job.test.yml
- for https://github.com/krassowski/jupyterlab-lsp/pull/452#issuecomment-755289990
- will re-target to #452 once green
Adds a `pip`-only install test to CI (doesn't even do a checkout). By making these rely on `lint` _and_ `build`, I'm hoping the acceptance jobs start first, so that this doesn't add to the bottom-line wall-clock time... even still, may want to cache pip, etc.
The existing `pip check` in the acceptance job is _still_ good to keep, as we want to know if our test dependencies have drifted or conflict with each other.
Ideally we'd _just_ install the `jupyterlab-lsp` tarball, to ensure the `install_requires` is configured properly, but I don't know how to make pip do that _and_ not pull in old versions of a locally-built dependency.
N/A, but should help non-dev installs go …
> Add pip-only install/CLI smoke test

- CHANGELOG.md
- atest/04_Interface/Statusbar.robot
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
which were not correctly scoped by path by switching away from `id_path` which was refactored to not contain the actual file path to `uri` which does contain the file path and `id_path`.
Fixes #469
> Fix connection manager loosing track of notebooks

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/completion.R
- docs/Configuring.ipynb
- python_packages/jupyter_lsp/jupyter_lsp/stdio.py
Fixes #450, enabling parsing of large responses from R server (e.g. completion on base) and any responses from javascript/typescript language servers
Turns out `BufferedIOBase.read()` does buffering... And we need to read in chunks until we consume all needed chunks.
Completion for R works better, completion for javascript works. May also help some Python packages with huge namespaces, e.g numpy. It will also improve perceived completion speed.
> Fix truncated stream

- CHANGELOG.md
- atest/05_Features/Completion.robot
- packages/jupyterlab-lsp/src/adapters/adapter.ts
Fixes #475.
Logic for handling re-connection after kernel restart was borked as it was only re-initializing a virtual document, whereas both virtual editor and virtual editor need to be re-initialised. This fixes it
New cells added after kernel restart work again.
None
> Fix handling of kernel change and restart

- CHANGELOG.md
- atest/04_Interface/BackendFailure.robot
- atest/Keywords.robot
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/errors.tsx
- packages/jupyterlab-lsp/src/manager.ts
- packages/jupyterlab-lsp/src/tokens.ts
- packages/jupyterlab-lsp/style/index.css
- packages/jupyterlab-lsp/style/statusbar.css
Fixes #453 and hopefully will reduce the influx of issues cause by the recent ecosystem changes.
- Added new status based on /lsp endpoint response code (only active for 404)
- the session retrieval now has 2 retries (10 second interval) to make it less likely that we refuse to cooperate when there was a temporary network issue, especially for users working over a proxy etc. It might be increased to more retries if we want to.
- Clicking on button opens dialog with useful info rather than a weird empty popup
- The new status uses red error color code
- Added test for backend failure which required to disable all global jupyter config when an argument is passed) as this was enabling the backend extension
> Add new status "no server extension"

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- python_packages/jupyterlab_lsp/setup.cfg
Release time :tada: 
Notes:
- failure on windows is limited to the new "Completes Large Namespaces" test case - Windows CI needs less strict timeouts, to be addressed after release
- known failure on Ubuntu with Python 3.6; pinning `jupyter_server==2.0.0` is known to solve the issue; the impact is limited to one pyls plugin; this was introduced by an upstream change and affects the older version too
> Prepare 3.1.0 and 1.1.0 release

- binder/environment.yml
Add `jupyterlab-classic` to the demo Binder, as there is now experimental support for it (#465)
Testing this PR with:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jtpio/jupyterlab-lsp/jupyterlab-classic-binder?urlpath=classic%2Ftree)
Binder changes
None
None
> Add jupyterlab-classic to the Binder

- CHANGELOG.md
- atest/04_Interface/DiagnosticsPanel.robot
- atest/05_Features/Completion.robot
- packages/jupyterlab-lsp/schema/syntax_highlighting.json
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_detect.py
- Fixes #475
- Allows to display the jedi-language-server diagnostics despite of the spec violation (related to #437)
- Fixes an issue with `PythonModuleSpec` when pyls is **not** installed:
```
Failed to fetch commands from language server spec finder`python-language-server`:
'NoneType' object has no attribute 'origin'
Traceback (most recent call last):
File "../lib/python3.8/site-packages/jupyter_lsp/manager.py", line 209, in _autodetect_language_servers
specs = spec_finder(self)
File "../lib/python3.8/site-packages/jupyter_lsp/specs/utils.py", line 96, in __call__
if not spec.origin:  # pragma: no cover
AttributeError: 'NoneType' object has no attribute 'origin'
```
> Various fixes

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/completion.R
- packages/completion-theme/src/index.ts
- packages/completion-theme/src/types.ts
- packages/completion-theme/style/index.css
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/features/completion/index.ts
- packages/jupyterlab-lsp/src/features/completion/renderer.ts
- packages/lsp-ws-connection/src/ws-connection.ts
- provides mechanism for mapping between some kernel types and LSP types for icons selection, fixes #333
- motivated by IJulia returning very different types than LSP types and IPython returning `<unknown>` if it cannot match a type
- implements `completionItem/resolve` to allow for:
- display of documentation panel with R language server which does not send documentation in the first request but requires `completionItem/resolve`
- faster completion (#272) once pyls or jedi-language-server implement `completionItem/resolve` too
- makes use of newly exposed `Completer.IRenderer`, for implementation of active item tracking and implements makrdown rendering of documentation in `Completer.IRenderer`
- add support for deprecation via `CompletionItemTag.Deprecated`
Related upstream PR:
- …
> Completer improvements: kernel type mapping and dynamic documentation

- CHANGELOG.md
- packages/jupyterlab-lsp/src/adapters/adapter.ts
Fixes #490.
- Julia server won't crash on save of non-Julia notebook/file.
- Performance will increase after save as only relevant connections are being notified
- Foreign documents will properly receive the save notifications, potentially improving some R language sever functions in `%%R` cells
None
> Fix Julia language server crashes on too broad save notification

- atest/04_Interface/Statusbar.robot
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
This is a backport of the fix from https://github.com/krassowski/jupyterlab-lsp/pull/474 to the `2.x` branch.
> Backport #474 to 2.x

- CHANGELOG.md
- README.md
- atest/03_Notebook.robot
- atest/04_Interface/Statusbar.robot
- atest/05_Features/Completion.robot
- atest/Keywords.robot
- atest/examples/Completion.ipynb
- atest/examples/Empty.ipynb
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/adapters/file_editor/file_editor.ts
- packages/jupyterlab-lsp/src/adapters/notebook/notebook.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/virtual/codemirror_editor.ts
Solves points: 1, 2 and 5 in #495.
- added a timeout for kernel completion (implemented as promise race)
- added a check of kernel status allowing user to choose to not wait for kernel if it is busy (by default the above timeout is used)
- the completions list could arrive after the cursor has moved; there was no check for the cursor change; the check is now added and if the cursor moved to another line or to an earlier character in the line the request will be invalidated (by an empty response mock)
- fixed issues related to handlers disposal/re-connection after kernel restart/file rename:
- `context.model.contentChanged` was not being re-connected after connection restart due to rename/kernel restart; this was the culprit of the (5) bug
- `editorAdded` and `editorRemoved` were never …
> More completer improvements

- atest/05_Features/Completion.robot
- python_packages/jupyter_lsp/jupyter_lsp/session.py
- python_packages/jupyter_lsp/jupyter_lsp/stdio.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_stdio.py
#450
This patch attempts to fix the truncated Jedi LSP responses which
produce warning messages about content-length mismatch. It does so
by looping around and trying again upon an empty read. The theory
is that the content producer is just not ready with more data yet.
- add function parameter 'max_empty_parts_in_a_row' with a default
value of 50.  This will be decremented on each empty read.
- change the default value of the 'max_parts' parameter to 100
since we should get larger chunks on each successful read.
Either of these values could be adjusted based on experience.
> Attempt to fix truncated Jedi LSP responses

- atest/03_Notebook.robot
- atest/04_Interface/DiagnosticsPanel.robot
- atest/04_Interface/Statusbar.robot
- atest/05_Features/Completion.robot
- atest/Keywords.robot
- atest/examples/Empty.ipynb
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/adapters/file_editor/file_editor.ts
- packages/jupyterlab-lsp/src/adapters/notebook/notebook.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/virtual/codemirror_editor.ts
Based on https://github.com/krassowski/jupyterlab-lsp/pull/498#issuecomment-770464899, backport more changes to the `2.x` branch.
Backports to `2.x`
> More backports to 2.x

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Release v2.1.3

- CHANGELOG.md
- atest/03_Notebook.robot
- atest/05_Features/Completion.robot
- atest/05_Features/Signature.robot
- atest/Keywords.robot
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/features/signature.ts
Invalidate completion result and signature just before displaying them if the current editor/cell lost focus; also invalidate signature if the cursor receded or changed line. Fixes 5.2 and 5.3 from https://github.com/krassowski/jupyterlab-lsp/issues/495.
- Added check of focus of active editor for completion and signature
- Added an argument for `handleSignature` to pass the cursor position at query time
- Added some debug messages
- Fixed kernel restart test missing restart
Signature and completions do not pop-up at unexpected times any longer
None
> Completion and signature invalidation

- packages/completion-theme/style/index.css
Fixes 13 from #495. The idea is that in extreme cases the completer covers the entire window width, which is annoying when someone has two files open side-by-side and looks at the other file, or has the context help open and wants to look at it; in other extreme cases the documentation panels get squished and is not usable.
Added CSS only; sadly not scoped to LSP as we cannot modify the completer class easily (needs changes upstream).
Before:
After:
- when item is not active it is collapsed at 400px with ellipsis indicator
- when item is active the completer gets expanded to a maximum of 600px
- when it is not enough the line breaks and the label gets wrapped on spaces
I do not like the wrapping behaviour too much though (suggestions welcome!).
None
> Limit the width of the completer items

- README.md
- python_packages/jupyter_lsp/jupyter_lsp/specs/pyls.py
without ' ' the command fails with:
no matches found: python-language-server[all]
> Fix install instructions in README

- CHANGELOG.md
- CONTRIBUTING.md
- atest/05_Features/Completion.robot
- atest/examples/completion.R
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/features/completion/item.ts
- packages/jupyterlab-lsp/src/features/completion/model.spec.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
- packages/jupyterlab-lsp/src/features/completion/renderer.ts
- implements sorting of completions solving point 4 of #495 by taking use of `sortText` if provided (jets tested and indirectly integration-tested)
- makes use of `filterText` if provided (jest tested)
- allows user to choose whether in presence of ties (i.e. two suggestions having the same match score) the kernel suggestions should go first or last (the latter by default) (integration tested)
- ensures that a full copy of item object gets created during filtering so that the documentation can still be retrieved dynamically (adds integration test for that)
- always re-renders the docpanel so that the markdown is always rendered (while waiting for https://github.com/jupyterlab/jupyterlab/pull/9663 to be merged)
- allows to render labels that contain HTML tags …
> Sorted completions, improve completions marking and filtering and doc panel

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/completion.py
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
Fixes #514 and point 7 in #495 
Split `suppressInvokeIn` setting into `suppressContinuousHintingIn` and `suppressTriggerCharacterIn`; added missing condition checks.
Completion in strings (keys of dict) works.
None
> Allow tab-invoked completion in strings, suppress autoinvoke in def

- CHANGELOG.md
- packages/jupyterlab-lsp/src/features/completion/model.spec.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
Only search for label match if different from insertText match and escape HTML label when no query is used.
Follow-up after #520 
- avoid matching again if the label prefix and insertText are the same
- escape HTML in label if no query is passed (so it is not removed by sanitizer)
- better filtering performance while retaining the benefit of using server-provided insertText
- completion of HTML/XML etc should work consistently
None
> Only search for label match if different from insertText match

- CHANGELOG.md
- packages/jupyterlab-lsp/src/components/utils.spec.ts
- packages/jupyterlab-lsp/src/components/utils.tsx
Fixes #515. The full path is displayed upon hovering over the collapsed path:
- Added react test for `get_breadcrumbs`
- Added code to collapse the breadcrumb path if more than three parts; assumes forward slash as the paths are normalized at this point
Before:
After:
Before:
After:
Adds a "collapse" toggle to `get_breadcrumbs`
> Collapse paths for files deep in subfolders

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/adapter_manager.ts
> Fix source install

- packages/jupyterlab-lsp/src/features/highlights.ts
Fixes #543 
onCursorActivity currently assumes that getCursor() will throw an exception if it was unable to obtain a valid cursor position. This is not the case. There are a few instances where it will return either undefined or null. In particular, if there is not yet an editor available. This change checks root_position and ensures it has a valid value.
none
none
> Handle case where getCursor() returns null in highlighter

- CHANGELOG.md
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.ts
Fixes #542
- fixed a typo (`s` where it should have been `\\s`)
- added a test
pinfo and pinfo2 magics will be correctly handled for IPython
None
> Fix a typo preventing pinfo from working on ids with letter 's'

- docs/Installation.ipynb
- scripts/integrity.py
`pip install jupyterlab-lsp=3.4.1` is missing one `=`
This is just a type in the docs, and I wanted to give you a heads up :)
> include second = for pip install

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/Completion.ipynb
- packages/jupyterlab-lsp/src/extractors/regexp.spec.ts
- packages/jupyterlab-lsp/src/extractors/regexp.ts
- packages/jupyterlab-lsp/src/extractors/testutils.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-bigquery/extractors.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/extractors.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/extractors.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-sql/extractors.ts
- packages/jupyterlab-lsp/src/transclusions/ipython/extractors.ts
- packages/jupyterlab-lsp/src/virtual/editor.spec.ts
Fixes #559
- splits `RegExpForeignCodeExtractor`'s `extract_to_foreign` into `foreign_capture_groups` and `foreign_replacer` (in a backward compatible way, with a deprecation notice for 4.0)
- corrects computation of offset (and thus ranges) for extracted documents by relying on `foreign_capture_groups` to determine start index; the old way was ok-ish for some extractors, but not a good general solution
Completion and other features will work more consistently in cell magics and line magics (and other extractors).
None, but deprecation notices added for `RegExpForeignCodeExtractor.extract_to_foreign` and `RegExpForeignCodeExtractor.keep_in_host`.
> Fix regular-expression based extractors offset

- CHANGELOG.md
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
- packages/jupyterlab-lsp/src/features/completion/item.ts
- packages/jupyterlab-lsp/src/features/completion/model.spec.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
- packages/jupyterlab-lsp/src/features/completion/renderer.ts
Small step towards #495 and #236. Fixes #492.
> Source-aware completions and more completer settings

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- python_packages/jupyterlab_lsp/jupyterlab_lsp/install.json
#568
Fixed the name of the package and the instructions on how to download it on the jupyterlab-lsp interface.
No backwards-incompatible changes.
> Change jupyterlab_lsp > jupyterlab-lsp

- CHANGELOG.md
- packages/code-jumpers/package.json
- packages/completion-theme/src/about.tsx
- packages/completion-theme/src/index.ts
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/editor_integration/codemirror.ts
- packages/jupyterlab-lsp/src/editor_integration/testutils.ts
- packages/jupyterlab-lsp/src/feature.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/diagnostics/index.ts
- packages/jupyterlab-lsp/src/features/diagnostics/listing.tsx
- packages/jupyterlab-lsp/src/features/highlights.ts
- packages/jupyterlab-lsp/src/features/jump_to.ts
- packages/jupyterlab-lsp/src/features/rename.ts
- packages/jupyterlab-lsp/src/features/syntax_highlighting.ts
- packages/jupyterlab-lsp/src/index.ts
any text displayed on the UI is made localizable using the TranslationBundle and ITranslator from @jupyterlab/translation
User will be able to use jupyterlab-lsp extension in prefered language given that the language pack is installed.
Can also be viewed by using the language settings to enable string prefix for all localized strings:
> localize strings for jupyterlab-lsp

- CHANGELOG.md
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
on Windows, even if cp1252, a Notebook must be written in utf-8.
Anaconda on Windows is not 'native', so doesn't have the problem.
shall solve https://github.com/krassowski/jupyterlab-lsp/issues/579
> patch jupyter_lsp-1.1.4 for 'native' Windows users

- atest/05_Features/Completion.robot
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
R got more methods starting with `data.frame.p`, trying to fix CI.
> Fix a test failing on CI as R got more methods

- CHANGELOG.md
- README.md
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
Some user love LSP for many of its features, but prefer to keep
completions via the kernel.
This adds two boolean flags in the configuration to not send completions
request to LSP and not send completions requests to the kernel.
#440  - I'm not sure how to toggle it on a per-notebook basis; I can likely add local state to LSPConnector which I guess is persisted on a per notebook basis but would welcome guidance on the best place to store that.
- Add 2 boolean to the setting. 
- turns those two booleans into properties on the LSPConnector, 
- when false skip requesting completions for the corresponding source.
None by default. User may disable one or two completer sources.
None
Note: I haven't touched typescript and frontend in years,  so I'm likely doing some things wrong;
> Allow to disable LSP or Kernel completions independently.

- CHANGELOG.md
- binder/environment.yml
- packages/_example-extractor/jest.config.js
- packages/jupyterlab-lsp/jest.config.js
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/adapter_manager.ts
- yarn.lock
Quick heads up that JupyterLab Classic has been renamed to RetroLab: https://github.com/jtpio/retrolab/issues/118
Opening the PR early as a draft to make sure it still works as expected with the lsp extension.
- Update the `@jupyerlab-classic` to `@retrolab`
- `IClassicShell` -> `IRetroShell`
None
None
> JupyterLab Classic -> RetroLab

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/schema/plugin.json
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/editor_integration/testutils.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.spec.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/hover.ts
- packages/jupyterlab-lsp/src/index.ts
- packages/lsp-ws-connection/package.json
- packages/lsp-ws-connection/src/types.ts
- packages/lsp-ws-connection/src/ws-connection.ts
- yarn.lock
Fixes #601 and updates lsp-ws-connection:
- use `import type` if possible
- update:
- "vscode-jsonrpc": "^6.0.0",
- "vscode-languageserver-protocol": "^3.16.0",
- "vscode-languageserver-types": "^3.16.0",
- "vscode-ws-jsonrpc": "0.2.0"
- remove unused code from lsp-ws-connection
- deprecate the `emit()` and getter based API for lsp-ws-connection
- add new API with well-typed:
```
public serverNotifications: ServerNotifications;
public clientNotifications: ClientNotifications;
public clientRequests: ClientRequests;
public serverRequests: ServerRequests;
```
> Implement console log window messages, update lsp-ws-connection

- README.md
There was a typo and it has been corrected.
> fix typo (pyslp -> pylsp) in README

- CHANGELOG.md
- packages/jupyterlab-lsp/schema/rename.json
None
Remove extra `'` which was leading to the shortcut not getting registered
F2 works in file editor.
None
> Fix rename shortcut in file editor

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/src/errors.tsx
- requirements/dev.txt
- requirements/lint.yml
Fixes #620 
Optimize lsp server error message
> Optimize lsp server error message

- CHANGELOG.md
- packages/completion-theme/package.json
- packages/completion-theme/src/index.ts
Relates to #272.
Bindprops early to avoid cache invalidation of LabIcon. JupyterLab since 2.1 has an ability to cache LabIcon svg strings (https://github.com/jupyterlab/jupyterlab/pull/8125) but we were not getting these benefits as using bindprops late in the code was causing a react proxy to be created and used which is preventing the caching mechanism from working.
The rendering time for long lists of completion items decrease notably:
- `pandas.<tab>` from 178 ms to 97ms (for list of 150 completions)
- `numpy.<tab>` from 1043 ms to 641 ms (for list of 1125 completions)
We should be able to improve this further with JupyterLab 3.1 since some of the current workarounds won't be needed any longer.
Before:
After:
Before
After
None
> Improve performance of icon rendering in completer

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/features/hover.ts
- packages/theme-material/package.json
- packages/theme-vscode/package.json
- yarn.lock
Fixes #628.
Fixes all three causes of missed cache hits:
- lack of coordination between requests (subsequent invokes sent while the old request was `await`ing)
- overlapping range for column (character) position in cache getter
- lack of safety check when storing data in cache
- No `console.warn` "spam"
- Hover should be slightly faster as we will be hitting cache more often
- Overall LSP should be slightly faster as we will be sending fewer requests on mouse move
None
> Fix hover malfunction messages

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- python_packages/jupyterlab_lsp/setup.cfg
Bumping frontend to 3.8 as there are new features added.
Bumping backend to 1.4 as the schema was extended. There are potentially breaking changes to `ShellSpec` but these pertain methods which were never advertised as public API (though they were not strictly private either). See CHANGELOG for details.
> Prepare jupyterlab-lsp 3.8.0 and jupyter-lsp 1.4.0 release

- CHANGELOG.md
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/extractors.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/extractors.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/overrides.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/overrides.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/rpy2.ts
- The `%R` magic could override non-R magics that started with `R`; this is now fixed and a test is added
- The `%Rdevice` magic which is why I originally found that bug was added
Better rpy2 integration
None
> Correct rpy2 `%Rdevice` magic integration

- CONTRIBUTING.md
- python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py
Fixes #640 - language server validator errors
Also updates broken link to configuring language server doc
Update `NodeModuleSpec` `__call__` function to resolve `argv` as an empty array when spec is not installed (same approach used in [PythonModuleSpec](https://github.com/krassowski/jupyterlab-lsp/blob/bba7fd1f3f10e93c2dc428bb19eb2959a9b29def/python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py#L81)).
This gets rid of `<ValidationError: "None is not of type 'string'">` messages, logged when `node_module` attribute is passed as `None` to `argv` array for any `NodeModuleSpec` not installed.
No more warnings logged for uninstalled language servers  when running lab using `--debug` .
None
> Fix warnings for uninstalled language servers

- requirements/lint.yml
Pin `robotframework<4.1` for lint step (see https://github.com/robotframework/robotframework/issues/4044) and use types-six from conda as this package is now available on conda-forge
> Pin robotframework for lint step on CI

- CHANGELOG.md
- atest/05_Features/Hover.robot
- atest/07_Configuration.robot
- atest/Keywords.robot
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/features/hover.ts
- fixes incorrect rendering of hovers provided as `MarkedString`s (which are deprecated but still supported)
- solves the difficulty of moving the mouse to the hover tooltip, by implementing a cushion of 50 pixels where mousleave/mousemove events do not trigger closing the tooltip
| before | after |
|--------|-------|
| ![before](https://user-images.githubusercontent.com/5832902/127781913-6fecd280-fa5a-4cc3-8849-b54def83681e.png) | ![after](https://user-images.githubusercontent.com/5832902/127781918-7138f809-ebe8-4a16-a598-561b291a1b67.png) |
| before | after |
|--------|-------|
| ![before-no-border](https://user-images.githubusercontent.com/5832902/127781896-4b0e3593-103c-4fa1-818c-de37fedf5f93.gif) | ![soft-border](https://user-images.githubusercontent.com/5832902/127781897-5a199ac1-b4c …
> Fix hover rendering for `MarkedString`s, fix hover disappearing when moving mouse towards it

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- python_packages/jupyter_lsp/jupyter_lsp/manager.py
- python_packages/jupyter_lsp/setup.py
- python_packages/jupyterlab_lsp/setup.py
- yarn.lock
Includes three minor improvements not worth a PR on their own (with the CI times in hours...):
- Reduce the number of logs from manager
- Add explicit package name in `setup.py`
- Bump pyright version
> Prepare release 3.8.1

- .gitignore
- packages/jupyterlab-lsp/src/components/utils.spec.ts
- packages/jupyterlab-lsp/src/editor_integration/testutils.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-bigquery/extractors.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-rpy2/extractors.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython-sql/extractors.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython/extractors.spec.ts
- packages/jupyterlab-lsp/src/virtual/document.spec.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
This fixes issue #543 which #544 fixed partially.
Add a check that `pos` isn't `null` before trying to access its properties.
> Handle case where position is null in document.ts

- packages/jupyterlab-lsp/src/components/statusbar.tsx
Fixes translations which should have used `trans`, not `this.model.trans`.
Translations will work for popover.
None
> Fix translations for popup

- packages/code-jumpers/src/jumpers/jumper.ts
This PR works around the issue #669 as described [here](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/669#issuecomment-981158541), by just removing the renaming of the tab, until there is a way to do it without actually renaming the files and breaking the envrioment:
Solves issue #669
```
$ git diff fix_jumping..upstream/master
diff --git a/packages/code-jumpers/src/jumpers/jumper.ts b/packages/code-jumpers/src/jumpers/jumper.ts
index 4237c7d..714af70 100644
--- a/packages/code-jumpers/src/jumpers/jumper.ts
+++ b/packages/code-jumpers/src/jumpers/jumper.ts
@@ -91,7 +91,7 @@ export abstract class CodeJumper {
private protectFromAccidentalEditing(document_widget: IDocumentWidget) {
let editor_widget = document_widget as IDocumentWidget<FileEditor>;
-    editor_widget.title.label = …
```
> fix renaming of file when jumping code

- README.md
This will allow for faster start-up for anyone who wants to try it out. Ideally the binder repos would get a tour and an example notebook catered to each language which are good "first issues".
> Add per-language binder demo links

- .github/workflows/job.test.yml
- atest/Keywords.robot
- atest/fixtures/jupyter_server_config.json
- python_packages/jupyter_lsp/jupyter_lsp/manager.py
- python_packages/jupyter_lsp/jupyter_lsp/types.py
An attempt to fix issues on CI seen when configuring/reconnecting to JupyterServer https://github.com/jupyter-lsp/jupyterlab-lsp/pull/711#issuecomment-981161263
I cannot reproduce it locally.
> Fix server extension UI test: migrate config to `ServerApp` as needed

- .github/workflows/job.test.yml
- CONTRIBUTING.md
- atest/04_Interface/DiagnosticsPanel.robot
- atest/examples/Panel.ipynb
- packages/jupyterlab-lsp/src/features/diagnostics/listing.tsx
- packages/jupyterlab-lsp/style/diagnostics_listing.css
Fixes #707
Improved sorting, added test.
Before:
After:
None
> Fix diagnostic listing sorting by cell/line, fix header border

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/conftest.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_listener.py
- We don't have jupyter-releaser integration in just yet, but it is still acceptable to watch the progress of this PR's GitHub Action listening to The Final Countdown (https://github.com/jupyter-server/jupyter_releaser/issues/202).
> Prepare jupyterlab-lsp 3.9.2 and jupyter-lsp 1.5.1 release

- CHANGELOG.md
- packages/completion-theme/package.json
- packages/jupyterlab-lsp/package.json
- yarn.lock
Follow up after #719 because #698 introduced a change in `completion-theme` package, so we cannot release 3.9.2 with that feature without bumping `completion-theme` first.
> Bump completion theme version, update release date

- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/virtual/codemirror_editor.ts
As highlighted in few issues, squashes some warnings:
- `TypeError: Cannot read properties of null (reading 'uri')` - this warrants a further investigation, looks like we have a regression and do dispose some connections properly so diagnostics keep coming; still this highlights a logic 
- `LSP: is_visible failed TypeError: Cannot read properties of undefined (reading 'virtual_line')` - context is sometimes requested when the document is not open yet, or already closed, we should handle it
- `TypeError: n is not a function` - this was an error in handling of a default arguments.
TODO:
> Squash warnings and errors in web console

- atest/05_Features/Signature.robot
- atest/examples/Signature.ipynb
- packages/jupyterlab-lsp/src/features/signature.spec.ts
- packages/jupyterlab-lsp/src/features/signature.ts
Follow up after #671:
- signature (and details) should be clickable but were not due to incorrect use of `target` where `relatedTarget` should be used
- label code was not rendering in signature for functions without arguments if details were present due to a missing new line
- use `relatedTarget` in blur event
- always add two new lines if details are, not only when highlighting active arguments
Before:
After:
None
> Fix signature blur and fix formatting when no arguments are present

- atest/05_Features/Completion.robot
- packages/jupyterlab-lsp/schema/completion.json
- packages/jupyterlab-lsp/src/features/completion/completion.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
Initial step for #728 - as we do not use `textEdit` just yet, we can get away with simple pre-filtering; in case if it is detrimental for some servers it can be disabled in the settings. This will be reworked once we solve https://github.com/jupyterlab/jupyterlab/issues/9763#issuecomment-1001603348.
Add `preFilterMatches` and pre-filter based on the token part derived from the current editor content and cursor position.
Completions will be usable in typescript server (among others).
None
> Enable simple pre-filtering of completion matches

- atest/05_Features/Diagnostics.robot
- atest/examples/Diagnostic.ipynb
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/lsp.ts
- packages/jupyterlab-lsp/style/highlight.css
- packages/lsp-ws-connection/src/ws-connection.ts
- requirements/github-actions.yml
Add support for diagnostic tags ([`DiagnosticTag`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticTag)) from LSP 3.15.
Adds two new CSS classes:
-  `cm-lsp-diagnostic-tag-Unused`
- `cm-lsp-diagnostic-tag-Deprecated`
moves `severity` determination code so it is not run if we don't need to update the diagnostic.
1. Strike-through is shown for deprecated items:
2. Unused code is faded out:
TBD
None
> Add support for diagnostic tags from LSP 3.15

- atest/05_Features/Diagnostics.robot
- atest/examples/Diagnostic.ipynb
- packages/jupyterlab-lsp/style/highlight.css
Follow up to #736
- use greyscale + stronger opacity for Unnecessary tag
- fix class name for Unnecessary
- add test case for Unnecessary using javascript for now
> Test unreachable code, fix style

- atest/05_Features/Completion.robot
- atest/05_Features/Diagnostics.robot
- atest/05_Features/Signature.robot
- docs/Extending.ipynb
- packages/jupyterlab-lsp/src/adapters/adapter.ts
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/connection_manager.ts
- packages/jupyterlab-lsp/src/editor_integration/testutils.ts
- packages/jupyterlab-lsp/src/feature.ts
- packages/jupyterlab-lsp/src/features/completion/index.ts
- packages/jupyterlab-lsp/src/features/diagnostics/index.ts
- packages/jupyterlab-lsp/src/features/hover.ts
- packages/jupyterlab-lsp/src/features/jump_to.ts
- packages/jupyterlab-lsp/src/features/signature.ts
- packages/jupyterlab-lsp/src/lsp.ts
This is a pre-requisite of #76 step 3, and enables third-party extensions to register the client capabilities they provide with the server (which is essential for some servers to return relevant responses).
- adds optional `capabilities?: ClientCapabilities` to `IFeature` public interface
- surfaces the capabilities from `connection` through `connection_manager` up to `adapter`
- in adapter the capabilities of active features are merged
- For servers which optimize responses/work based on client capabilities the performance might be slightly increased when specific features are disabled
None
> Move client capabilities to features

- atest/03_Notebook.robot
- atest/05_Features/Completion.robot
- atest/07_Configuration.robot
- atest/Keywords.resource
- binder/overrides.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/texlab.schema.json
- scripts/atest.py
JupyterLab 3.3 uses "Advanced JSON Setting Editor" instead of "Advanced Setting Editor" - should fix some failing tests.
Another change will be needed for JupyterLab 4.0 where it will become just "JSON Setting Editor".
Additionally, updates texlab support (version 3.x).
> Fix tests for JupyterLab 3.3

- packages/jupyterlab-lsp/src/features/jump_to.ts
- packages/jupyterlab-lsp/src/utils.ts
Backport of 14ece08e295ff7bb8a5f7197c08e120547d57b40 to 3.x branch
> Backport "Fix jumping to dependencies in node modules" on 3.x

- packages/metapackage/package.json
- requirements/github-actions.yml
- yarn.lock
Bump typedoc version to drop some very outdated dependencies from lockfile. Typedoc results are not currently in use, but let's aim at integrating it in 4.0.
> Bump (not yet in use) typdoc version

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Prepare jupyterlab-lsp 3.10.1 release

- README.md
My understanding of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/272#issuecomment-891286446 is that these changes how now been merged into the `python-lsp` conda package and there is no need to install the forked language server separately, is this correct? 
Does that mean that the recommended way to install `jupyterlab-lsp` including all the speed-ups is just:
```
conda install jupyterlab-lsp python-lsp-server
```
And there is no need to disable Jedi, since the updates to the pylsp also improved the slow Jedi calls? 
I have some issues with completion speed and can open a ticket with more info, but I just wanted to make sure that I followed the recommended installation procedure first.
> Remove note about language server fork

- .github/workflows/job.test.yml
- CONTRIBUTING.md
- binder/environment.yml
- docs/rtd.yml
Node 12 reached EOL in April.
Required for bumping of tested servers (in #778) as some dropped support for 12.0 already.
> Increase minimum Node.js to 14.0

- README.md
`Note 2` was removed from `README.md` in e8635f823d2a88207991d7d5d85a28699e3aa3b8, however two references to this fork remained in the README.  This PR removes the references to the note that no longer exists to avoid potential confusion for users who are installing `jupyterlab-lsp`.
N/A
N/A 
N/A
N/A
_**Not completing chores because this PR simply removes three lines to one markdown file only.**_
> Remove orphaned references to the fork of python-language-server in README.md

- CHANGELOG.md
- packages/jupyterlab-lsp/src/features/completion/completion_handler.spec.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
Fixes #832
Completion of `import { Signal } from @lumino/<tab>` will work correctly.
> Fix LSP completion transform of path-likes when `insertText` missing

- packages/jupyterlab-lsp/src/features/completion/completion_handler.spec.ts
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
Backport PR #833: Fix LSP completion transform of path-likes when `insertText` missing.
> Backport PR #833: Fix LSP completion transform of path-likes when `insertText` missing

- packages/jupyterlab-lsp/src/editor_integration/codemirror.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/highlights.ts
- Use `.operation()` for setting CodeMirror5 marks; should also help with porting to CM6 (where `RangeSets` will take over some of the responsibility)
- deprecate `highlight_range` and `highlight_markers` protected properties.
Improved performance when more than one diagnostic of highlighted element present in editor; especially noticeable in notebooks as the cost of relayout there is much higher, but also noticeable in file editor for large scripts.
- one cell with 1000 `math.pi` and `import math`; move cursor to `math`, wait for 1000 highlights, then move to `pi`:
- before:
- highlight `math`: 13.1s
- then highlight `pi`: 16.6s
- after:
- highlight `math`: 160ms
then highlight `pi`: 227ms
- 100 cells with `math.pi` and one with `import math`; move cursor to `math`, wait for 1000 …
> Improve performance of diagnostics and highlights

- package.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/bash-language-server.schema.json
- requirements/atest.txt
- requirements/atest.yml
- yarn.lock
Closes #839 - from now on the main branch will be testing against bash language server 3.1.
None
- corrected default for `highlightParsingErrors`
None
> Update bash language server to v3.1

- CHANGELOG.md
- README.md
@krassowski As per #828, here's a draft.
I've left the unix-only part in the instructions. I am, however, unsure about why this wouldn't affect Windows users. Do you have any more insight on this?
> Fix instructions for .lsp_symlink workaround

- packages/jupyterlab-lsp/src/components/free_tooltip.ts
One test was failing in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/855 since JupyterLab 3.4.7 release due to an improvement in hoverbox positioning.
This PR takes advantage of the new positioning by changing host of tooltips to notebook and fixing CI.
> Improve tooltips with refined `HoverBox` positioning in 3.4.7

- atest/07_Configuration.robot
- atest/Keywords.resource
- atest/Variables.resource
- atest/fixtures/jupyter_server_config.json
- atest/fixtures/jupyter_server_config.py
- atest/fixtures/overrides.json
- packages/jupyterlab-lsp/src/components/serverSettings.tsx
- packages/jupyterlab-lsp/src/index.ts
- packages/jupyterlab-lsp/src/settings.ts
- packages/jupyterlab-lsp/style/index.css
- python_packages/jupyter_lsp/jupyter_lsp/schema/schema.json
Closes #821
- add optional `workspace_configuration` to language server spec which defines defaults for `workspace/configuration` reply (also known as `serverSettings`)
- split `SettingsSchemaManager`  from `SettingsUIManager` (non-breaking as this was never released)
The settings UI will notify of any defaults set by the server.
None
> Allow to pass default workspace config (`serverSettings`) in specs

- binder/postBuild
- packages/jupyterlab-lsp/jest.config.js
- packages/jupyterlab-lsp/src/connection.ts
- packages/jupyterlab-lsp/src/jest-shim.ts
- packages/lsp-ws-connection/package.json
- packages/lsp-ws-connection/src/ws-connection.ts
- packages/lsp-ws-connection/webpack.config.js
- yarn.lock
Fixes #854
- removes wokraround from #855
- upgrades to webpack 5.54 which supports alternative hashing algo
- upgrades vscode-ws-jsonrpc (needed since no node.js shims in webpack 5 anymore) and adds necessary shims for jest (those are in testutils of lab 4.0 so can be removed in the future)
- Possibly faster load time as less polyfils included.
- Browsers must [support `TextEncoder`/`TextDecoder`](https://caniuse.com/textencoder) (also required by JupyterLab 4 debugger)
None
> Bump webpack in ws lsp connection

- atest/05_Features/Completion.robot
- python_packages/jupyter_lsp/jupyter_lsp/specs/julia_language_server.py
- python_packages/jupyter_lsp/jupyter_lsp/specs/pyright.py
- python_packages/jupyter_lsp/jupyter_lsp/specs/typescript_language_server.py
- scripts/lint.py
Increase robustness of CI completion tests without addressing the underlying issue in adapter setup as that will go away once we migrate to JupyterLab 4.0 native completion.
> Fix flaky completion tests

- CHANGELOG.md
- atest/05_Features/Signature.robot
- atest/examples/Signature.ipynb
- packages/jupyterlab-lsp/src/components/free_tooltip.ts
- packages/jupyterlab-lsp/src/features/hover.ts
- packages/jupyterlab-lsp/src/features/signature.ts
Fixes #834
`EditorTooltipManager` gest new methods: `showOrCreate`, `show`, `hide`
Signature tooltip will be hidden (rather than removed) if we know that we will be showing it again soon; if it has not changed (nor position, editor, etc), it will be shown as-is, if only content changed it will be updated.
Unfortunately, pylsp seems to return a message with empty signature every other time which is the direct cause of flickering in remaining instances.
> Reduce signature and hover flickering

- CHANGELOG.md
- atest/05_Features/Hover.robot
- atest/Variables.resource
- packages/jupyterlab-lsp/schema/hover.json
- packages/jupyterlab-lsp/src/features/hover.ts
- python_packages/jupyterlab_lsp/setup.py
**[EDIT]** Screenshot replacement after the config rewording.
https://github.com/jupyter-lsp/jupyterlab-lsp/issues/362
* Wait for `delay` period before showing a hover tooltip IF `autoActivate` is enabled.
* Fix `TypeError` warning by taking care of types.
Add 'Automatic hover' and 'Hover delay' to 'Code Hover' in Advanced Setting Editor. They are disabled by default.
Here is a screenshot:
None.
> Add option to show up hover tooltip automatically

- .github/workflows/job.test.yml
- atest/01_Editor.robot
- atest/04_Interface/BackendFailure.robot
- atest/04_Interface/DiagnosticsPanel.robot
- atest/05_Features/Completion.robot
- atest/05_Features/Diagnostics.robot
- atest/05_Features/Highlights.robot
- atest/05_Features/Hover.robot
- atest/05_Features/Jump.robot
- atest/05_Features/Signature.robot
- atest/05_Features/Syntax_highlighting.robot
- atest/06_Style.robot
- atest/07_Configuration.robot
- atest/Keywords.resource
- atest/__init__.robot
- atest/examples/example.robot
- docs/Language Servers.ipynb
- requirements/github-actions.yml
An attempt to fix CI failure seen in #867
> Add notebook dependency to CI to test `serverextension`, fix CI

- requirements/github-actions.yml
Attempt to fix failure seen in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/888 and https://github.com/jupyter-lsp/jupyterlab-lsp/pull/636
> Add temporary pin on `pytoolconfig` to fix `pip check`

- CHANGELOG.md
- packages/completion-theme/style/index.css
- packages/jupyterlab-lsp/src/features/completion/renderer.ts
Elide long path completions, fixes #787 and fixes https://github.com/jupyterlab/jupyterlab/issues/12830
The content of the first highlighted (`<mark>`ed) part is elided for paths
- `direction: rtl` is used to reverse side of eliding
- to prevent wrong placement of neutral BiDi characters (e.g. `.` or `/`) `<bdo>` tag wrapper is used for `<mark>` contents; the alternative, CSS `unicode-bidi` would also require an HTML wrapper, hence BDO tag is a simpler choice.
- `display:flex`/`flex-shrink: 1` is used to stretch the mark to as much as possible
I also explored a possibility of eliding of the middle part of the path based on separator, but there does not appear to be a good solution (which would have good performance with large number of matches).
Long paths are elided. User can hover over …
> Implement eliding for paths/files

- CHANGELOG.md
- atest/07_Configuration.robot
- atest/Keywords.resource
- atest/fixtures/jupyter_server_config.py
- atest/fixtures/overrides.json
- atest/paths.py
- packages/jupyterlab-lsp/src/settings.ts
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/pyright.schema.json
Fixes #918
- include defaults from overrides (provieded via schema) in composite defaults
- update/fix pyright schema (addressing warning in check added with above checking for defaults not aligning with schema)
- `overrides.json` will work
- pyright settings from UI will work
None
> Fix `overrides.json` not being picked up in defaults

- atest/07_Configuration.robot
Address failure seen in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/927 and described in https://github.com/jupyter-lsp/jupyterlab-lsp/issues/894#issuecomment-1510410526
Updated expected diagnostic value
None
None
> Update texlab expectation

- packages/jupyterlab-lsp/src/features/jump_to.ts
Fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/823
Only trigger jump-to-definition when mouse up is used.
Creating rectangular selections with Alt + click + drag work.
None
> Fix conflict with block/rectangular selections on Alt + click

- docs/Configuring.ipynb
- packages/jupyterlab-lsp/src/connection_manager.ts
- python_packages/jupyter_lsp/jupyter_lsp/schema/schema.json
- python_packages/jupyter_lsp/jupyter_lsp/serverextension.py
- python_packages/jupyter_lsp/jupyter_lsp/specs/pyright.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_virtual_documents_shadow.py
- python_packages/jupyter_lsp/jupyter_lsp/types.py
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
Closes #537. Related to #924.
- adds new `requires_documents_on_disk` field in the specs (`True` by default for now, will become `False` in next major version)
- publicly exposes `language_servers: KeyedLanguageServerSpecs` API member of the manager
- updates types to for listeners to give access for full exposed manager API for `manager` argument
- marks following servers as not requiring documents on disk: Pyright
No `.virtual_documents` when only using servers which do not require it. If at least one of installed servers requires `.virtual_documents`, it may still be created, but the creation will be delayed until such a server is actually in use.
None
> Make `.virtual_documents` optional

- python_packages/jupyter_lsp/jupyter_lsp/tests/test_virtual_documents_shadow.py
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
Addresses https://github.com/jupyter-lsp/jupyterlab-lsp/issues/924#issuecomment-1531183986
- limit the shadow FS initialisation to three attempts
- emit a warning with suggestions if third attempt fails
- add a test for permission error
None unless affected by https://github.com/jupyter-lsp/jupyterlab-lsp/issues/924
None
> Limit the shadow FS initialisation to three attempts

- packages/jupyterlab-lsp/schema/diagnostics.json
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.spec.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
Closes #751
Adds `ignoreSeverities` setting
New setting:
None
> Add `ignoreSeverities` setting

- python_packages/jupyter_lsp/jupyter_lsp/manager.py
In jupyter-lsp 2.1.0, when I open the jupyterlab page, the terminal give me a warning
```
/root/miniconda3/lib/python3.8/site-packages/jupyter_lsp/manager.py:130: RuntimeWarning: coroutine 'sleep' was never awaited
asyncio.sleep(0.1)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
And then the process is stuck (and cpu 100%).
I notice that the coroutine `asyncio.sleep` is not sleeped here and it should be fixed.
https://github.com/jupyter-lsp/jupyterlab-lsp/blob/fee5ce6de8da23c9d00eb201d305a120a5e747a3/python_packages/jupyter_lsp/jupyter_lsp/manager.py#L128-L131
I add a `await` before `asyncio.sleep(0.1)` to fix it.
> Await sleep coroutine while waiting for manager to be ready

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
Small changeset this time, possibly last point release before switching gears toward 5.0 rewrite/JupyterLab 4.0 compatibility (help wanted)
> Prepare jupyterlab-lsp 4.2.0 and jupyter-lsp 2.2.0 releases

- packages/jupyterlab-lsp/src/features/diagnostics/index.ts
Fixes #167
- adds optional dependency on `ILayoutRestorer`,
- adds tracker to facilitate restoration
Diagnostics panel is preserved when reloading JupyterLab
None
> Restore diagnostics panel on refreshing

- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/jump_to.ts
- packages/jupyterlab-lsp/src/features/rename.ts
Follow up to #949 - use transient notifications to avoid spamming the notification centre.
- adds `autoClose` option where needed replacing manual `Notificaiton.dismiss` calls
| Before | After |
|---|---|
| ![before](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/5832902/6e7942c7-b2b7-4462-b2e4-5cf9bde5197b) | ![after](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/5832902/974b7ad3-bc70-4a03-996c-01b0572d0587) |
None
> Automatically show and dismiss notifications

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/features/completion/overrides.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/diagnostics/feature.ts
- packages/jupyterlab-lsp/src/features/diagnostics/listing.tsx
- packages/jupyterlab-lsp/src/features/diagnostics/tokens.ts
- packages/jupyterlab-lsp/src/features/rename.ts
- packages/jupyterlab-lsp/style/highlight.css
- packages/jupyterlab-lsp/style/variables/base.css
- packages/metapackage/package.json
Closes #969 
Closes #974 
Closes #973 
- implements `isApplicable` for kernel completion provider override
- switches to editor wrapper in diagnostics listing to enable scrolling to out-of-view cells
- improves support for windowed notebook but it is still imperfect (diagnostics may be not rendered if scrolling fast and then coming back)
Changes the colour of highlights to slightly darker and removes dotted outline. Feedback welcome.
`IEditorDiagnostic` now uses `editorAccessor` instead of `editor`.
> Fix issues identified in 5.0.0b0, prepare 5.0.0b1

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/virtual/document.ts
- packages/metapackage/package.json
Workaround for #959 which should also reduce #988 to the upstream issue and unblock release of 5.0 without disabling transclusions support.
Override `chooseForeignDocument` method of virtual document to restore re-use of unused standalone documents.
None
None
> Restore re-use of unused standalone connections

- CHANGELOG.md
- atest/01_Editor.robot
- atest/04_Interface/DiagnosticsPanel.robot
- atest/05_Features/Completion.robot
- atest/05_Features/Hover.robot
- atest/07_Configuration.robot
- docs/Language Servers.ipynb
- packages/code-jumpers/package.json
- packages/completion-theme/package.json
- packages/jupyterlab-lsp/package.json
- packages/theme-material/package.json
- packages/theme-vscode/package.json
- yarn.lock
- Fixed integration tests
- Integration tests skipped due to known upstream issues:
- Integration tests skipped as passing locally (help wanted):
Many of the tests will not be fixed before JupyterLab 4.1 gets released because of how unreliable is the workaround of getting the adapter.
> Final pass before 5.0 release

- python_packages/jupyter_lsp/jupyter_lsp/tests/test_stdio.py
> Use `sys.executable` in stdio tests

- python_packages/jupyter_lsp/jupyter_lsp/handlers.py
when deploy jupyter-lsp on server, the GET request may need handle the CORS problem, which means handle OPTIONS request properly.
- handle CORS Options request in the same way with jupyter-server
> fix: handle CORS OPTIONS request

- atest/diagnostics.py
- atest/mouse_over_extension.py
- python_packages/jupyter_lsp/jupyter_lsp/manager.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_paths.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_stdio.py
- python_packages/jupyter_lsp/jupyter_lsp/trait_types.py
- python_packages/jupyter_lsp/jupyter_lsp/types.py
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
- requirements/dev.txt
- requirements/lint.yml
- Fixes a few mypy/traitlets interaction issues due to new traitlets version as seen in #1007 and others.
- Removes implicit `six` dependency and `types-six` requirement for linting
- Lints robot scripts too
> Resolve traitlets type warnings, lint, remove `six`

- CHANGELOG.md
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.spec.ts
- packages/jupyterlab-lsp/src/transclusions/ipython/overrides.ts
In this PR, I want to fix #635. 
According to the comment in #635, I implemented another transformation to the specific cell magics.
From:
```py
%%capture --no-display
x = 1
```
To:
```py
x = 1
```
Instead of:
```py
get_ipython().run_cell_magic("capture", "--no-display", """x=1""")
```
Currently, the target cell magics are hard coded (%%time, %%capture).
It would be better if the list is configurable.
Since I'm new to the project, I need more time to figure out how to make the list configurable, but I will try this in the near future.
As pointed out in #635, variables defined inside cell magics are not recognized by the lsp, and `undefined name` message shows up.
This PR tries to remove these false messages.
No
> Fix false “undefined name” message caused by cell magic

- packages/jupyterlab-lsp/src/edits.ts
- python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
> Workaround issue with markdown lost on edit

- package.json
- yarn.lock
Fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1017
Switched to build-in yarn dedupe instead of a third-party package; it only offers the `highest` strategy and while there is a port of the old package (https://github.com/yarnpkg/berry/issues/2297#issuecomment-1524052855) I prefer to keep it simple to reduce maintenance. Shall we need to dedupe further we can always run `jlpm dlx yarn-berry-deduplicate`
Removed `lerna bootstrap` as it is not supported for berry+ and it seems there is no interest from current lerna maintainers:
- https://github.com/lerna/lerna/issues/2910
- https://github.com/lerna/lerna/issues/2449
> Fix bootstrap script

- packages/jupyterlab-lsp/jest.config.js
- packages/jupyterlab-lsp/src/features/completion/model.spec.ts
- packages/jupyterlab-lsp/src/features/completion/model.ts
- fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1014
- fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1009
- fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/704
Moves pre-filtering to LSP model which now checks if the item came from LSP
> Do not pre-filter completions from kernel

- packages/jupyterlab-lsp/src/features/completion/overrides.ts
- packages/jupyterlab-lsp/src/features/completion/provider.ts
Fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1006
Check if we can access `path` of the widget rather than assuming it is always 
Kernel/context completions in console are no longer broken (although LSP completions are still not available)
None
> Fix completion provider `isApplicable()` for Console

- packages/jupyterlab-lsp/src/utils.spec.ts
- packages/jupyterlab-lsp/src/utils.ts
This might fix #1005
Normalize the path in `uriToContentsPath` before checking whether to remove server root prefix.
Jump to definition for files in root dir should work on Windows with Pyright.
None
> Normalize Windows path to fix jump to definition with Pyright

- packages/completion-theme/style/index.css
- packages/jupyterlab-lsp/src/features/completion/renderer.ts
Fixes #1002
The issue was that:
- (a) heuristic did not account for eliding
- (b) styles limiting the width were not applied when the widest item size was calculated after temporarily re-parenting to `<body>`
- (c) there was no limit on ellipsis width (now its 50% of label)
- (d) the label size limit maybe was too low, it got increased by 50px
Eliding of paths works better. There should be no empty (unutilised) space in the completer anymore
None
> Improve item width size estimation heuristic support

- packages/jupyterlab-lsp/src/settings.spec.ts
- packages/jupyterlab-lsp/src/settings.ts
Follow-up to #919
Prefer user-set `priority` over the overrides and defaults. Prefer overrides over defaults.
`priority` can be changed from settings when it was pre-set with `overrides.json`.
None
> Fix overrides `priority`

- packages/jupyterlab-lsp/src/features/completion/renderer.ts
- setup.cfg
Fixes #1043 
- add better typing to catch potential issues
- resolve the issues highlighted by improved typing
Context completions work again
None
> Fix completions when `type` is not defined

- packages/jupyterlab-lsp/src/virtual/document.ts
Follow-up to https://github.com/jupyterlab/jupyterlab/pull/15105
Remove reference to upstream variable `unusedDocuments`; this variable was removed in `JupyterLab 4.0.7` (as it should have never been there)
Transclusions should work more reliably in newer lab versions
None
> Fix transclusions in JupyterLab 4.0.7+

- package.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/typescript_language_server.py
- yarn.lock
Looking into using `typescript-language-server` and following the [docs to install it](https://jupyterlab-lsp.readthedocs.io/en/latest/Language%20Servers.html#example-getting-all-the-node-js-based-language-servers), it looks like `jupyter_lsp` was not able to find the language server:
Updating the script seems to be fixing it:
Update the `script` for `typescript-language-server`.
Users can install and use `typescript-language-server` with JupyterLab LSP.
This supports the latest version of `typescript-language-server`, but might break previous versions when the file was still `cli.js`?
> Update `script` for `typescript-language-server`

- CHANGELOG.md
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- python_packages/jupyter_lsp/jupyter_lsp/session.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_session.py
Closes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1076
Use `os._Environ.copy` instead of `copy.copy` to copy the environment
None
None
> Fix environment variables leaking into the parent environment

- packages/jupyterlab-lsp/src/edits.ts
- yarn.lock
Fixes #1084
Adds short-circuit for raw cells
Renaming does not remove contents of raw cells
None
> Fix rename causing blanking of raw cell conents

- .github/workflows/job.test.yml
Looking into https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1111
> Fix usage of `conda-incubator/setup-miniconda`

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/src/features/hover.ts
- yarn.lock
Fixes #1113
Bail early on mouse motion DOM event handler if the widget adapter is not connected.
This avoid doing DOM computation and displaying noisy log file on file not supporting LSP.
**Before**
https://github.com/user-attachments/assets/13925c4c-3eb2-466d-b30a-159d9b8ac985
**After**
https://github.com/user-attachments/assets/fcfb462f-e6f4-4b10-a182-a046b727f27d
None
- documented
> Don't test for cursor position on `mousemove` if the widget adapter is not connected

- docs/Configuring.ipynb
The old link is dead, edited from the Github web UI
> Fix URL in docs

- .github/workflows/job.test.yml
- atest/suites/03_Notebook.robot
- atest/suites/05_Features/Highlights.robot
- atest/suites/07_Configuration.robot
- packages/jupyterlab-lsp/schema/plugin.json
- packages/jupyterlab-lsp/src/components/statusbar.tsx
- packages/jupyterlab-lsp/src/index.ts
- python_packages/jupyter_lsp/jupyter_lsp/tests/test_paths.py
Toolbar item can now be disabled
- Deprecates `StatusButtonExtension.createNew` that was used by docregistry to add toolbar items
- Adds `StatusButtonExtension.createNewToolbarItem` to be used with schema-based toolbar definitionn
Users can disable this icon when running in Notebook interface <img width="42" height="46" alt="image" src="https://github.com/user-attachments/assets/b8552b21-1a77-474f-9cf1-125b11263d67" />
None
> Allow to disable LSP toolbar item in Notebook view

- CHANGELOG.md
- python_packages/jupyter_lsp/jupyter_lsp/specs/__init__.py
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/README.md
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/pyrefly.schema.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/pyrefly.py
- python_packages/jupyter_lsp/setup.cfg
Closes #1136 
- Add LSP specification for Pyrefly: https://pyrefly.org/
- Exposes two settings also referenced in the package.json for the VS Code extension: https://github.com/facebook/pyrefly/blob/main/lsp/package.json
- Exposes diagnostics and other LSP operations from Pyrefly
- ~Change in review for supporting didChangeConfiguration notifications with settings since Jupyter Lab doesn't use `workspace/configuration` requests~
- Thanks for maintaining this project!
> Add Pyrefly LSP specification
