- src/command_manager.ts
> Fix #31 (LSP commands in context menu when clicked outside of editor)

- py_src/jupyter_lsp/README.md
Up for discussion, but I think that this is a bit easier to read.
Also, corrected second css to sass.
> Compactify the language servers tables

- atest/01_Editor.robot
- atest/Keywords.robot
- atest/Variables.robot
- ci/job.combine.yml
- ci/job.test.yml
- ci/steps.conda.yml
For #68 flake... will squash merge once passing.
> More ci flake fixes 🤖📦❄️

- py_src/jupyter_lsp/CONTRIBUTING.md
Having a clean install of a new OS is a good time to check how good are the instructions.
> [WIP] Minor updates to CONTRIBUTING.md

- packages/jupyterlab-lsp/src/adapters/codemirror/cm_adapter.spec.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/feature.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/rename.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/testutils.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/components/statusbar.tsx
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
Minor improvements to the statusbar; enables more verbose features to give the user some feedback.
> Add message notifications to statusbar, tidy it up

- CONTRIBUTING.md
If there is a better way, please let me know!
> Add a command to run specific frontend tests only

- CONTRIBUTING.md
> add lab cleaning to acceptance test troubleshooting

- CHANGELOG.md
- azure-pipelines.yml
- packages/jupyterlab-lsp/package.json
- packages/lsp-ws-connection/package.json
- packages/metapackage/package.json
- py_src/jupyter_lsp/_version.py
Zeroth beta release so that I (and others) can test it while working on real projects (also, because it fixes some important bugs and I need it working ;). I will write note down any potential issues with the release process here.
> Release jupyterlab-lsp 0.7.0-beta0, jupyter-lsp 0.7.0b, lsp-ws-connection 0.3.0

- packages/jupyterlab-lsp/src/adapters/codemirror/cm_adapter.spec.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/feature.spec.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/feature.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/completion.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/diagnostics.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/highlights.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/hover.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/jump_to.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/rename.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/features/signature.ts
- packages/jupyterlab-lsp/src/adapters/codemirror/testutils.ts
- packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts
Closes #133.
- [-] documented
- [-] changelog entry
> Add name attributes to features, make CodeMirrorLSPFeature abstract

- atest/01_Editor.robot
More tests for the rename feature #131.
> Enable rename testing for more LSP servers, reduce time lag

- CHANGELOG.md
- packages/jupyterlab-lsp/src/extractors/defaults.spec.ts
- packages/jupyterlab-lsp/src/extractors/defaults.ts
- packages/jupyterlab-lsp/src/extractors/regexp.ts
- packages/jupyterlab-lsp/src/magics/defaults.ts
- packages/jupyterlab-lsp/src/magics/rpy2.spec.ts
- packages/jupyterlab-lsp/src/magics/rpy2.ts
- packages/jupyterlab-lsp/src/virtual/document.ts
`%R` and `%%R` magics will now correctly parse arguments, including creating dummy input variables allowing for better diagnostics.
Test suite for default virtual extractors was created allowing for future improvement in the test coverage of various scenarios of code extraction.
None
None
> Enhanced argument parsing in rpy2 magics

- CONTRIBUTING.md
- atest/05_Features/Completion.robot
- scripts/atest.py
- fixes #151
Will output what the arguments would have been for `robot`. Sorta.
None
None
> add some docs for customizing robot run

- CHANGELOG.md
- azure-pipelines.yml
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
No changes apart from the version bump. PR to check if the CI will pass.
> Release 0.7.1

- CHANGELOG.md
- azure-pipelines.yml
- packages/jupyterlab-lsp/package.json
- packages/lsp-ws-connection/package.json
- packages/metapackage/package.json
- py_src/jupyter_lsp/_version.py
> Release v0.8.0

- CONTRIBUTING.md
- LANGUAGESERVERS.md
- README.md
> Add documentation links in LANGUAGESERVERS & README

- README.md
May help solve #200 and #203 for some users.
None
None
None
> Add notes on pyls dependencies issues

- CONTRIBUTING.md
> Update CONTRIBUTING.md - postBuild moved

- .travis.yml
Follow up on https://github.com/krassowski/jupyterlab-lsp/pull/245#issuecomment-615356132.
> Allow osx failures on Travis

- requirements/utest.txt
> Fix Travis with Python 3.5

- docs/_static/css/custom.css
- docs/conf.py
Fixes #249 and #221, using the workaround from https://github.com/clberube/bisip2/commit/810c70bc04cba016b6f3fbe6e2412bd689acf1a8
> Documentation style updates

- CHANGELOG.md
- atest/03_Notebook.robot
- atest/examples/Code overrides.ipynb
- packages/jupyterlab-lsp/src/overrides/index.ts
Fixes #339. Actually it was just pure luck that some cell magics kept working...
No significant changes.
Diagnostics will again work in IPython :)
None
I will do a release immediately from here.
> Fix code overrides & add an acceptance test

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
A bug fix release improving handling of IPython magics.
> Release v2.0.3

- README.md
- binder/environment.yml
- docs/rtd.yml
- requirements/github-actions.yml
Removes outdated dependency pin as noted in #354.
> Remove ujson pin

- docs/Installation.ipynb
- scripts/integrity.py
> Fix pip install version pin using = rather than ==

- atest/05_Features/Completion.robot
It's just a guess, nothing more.
> Attempt to fix TabError failures on CI

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Release v2.0.8

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Release v2.1.2

- .github/workflows/job.test.yml
- python_packages/jupyterlab_lsp/jupyterlab_lsp/_version.py
- python_packages/jupyterlab_lsp/setup.py
Minor changes preparing for rc0 release.
> Prepare for jupyterlab_lsp rc0

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/Installation.ipynb
- scripts/integrity.py
> Release 3.0.0

- CHANGELOG.md
- atest/05_Features/Completion.robot
- atest/examples/completion.R
- packages/jupyterlab-lsp/src/features/completion/completion_handler.ts
> Fix R double (and triple) colon completion issue

- CHANGELOG.md
- packages/completion-theme/src/index.ts
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/schema/completion.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- scripts/integrity.py
> Release 3.2.0 and 1.1.1; improve integrity check for install_requires

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
Release time :tada:
Also enabling CI builds on 2.x.
> Release 3.3.0 and 1.1.2

- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Release v3.4.1

- README.md
> Describe the pyls fork and IPython Jedi setting in README

- README.md
Closes #531 
Updates location to configure IPython not to use jedi for completion
> change IPython config location for use_jedi

- CHANGELOG.md
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
Note: no frontend release this week.
> Release jupyter-lsp v1.1.4

- packages/jupyterlab-lsp/src/features/highlights.ts
Backport #544 by @brendan0powers to the `2.x` branch.
> Backport #544 to the 2.x branch

- .github/workflows/job.test.yml
- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
This release only includes the backport of #544.
Bug fix for users of the  `2.x` series.
None
> Release v2.1.4

- CHANGELOG.md
- packages/_example-extractor/package.json
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Release v3.5.0

- CONTRIBUTING.md
> cool-language-server example: Fix Python syntax error

- packages/jupyterlab-lsp/src/manager.ts
> Only emit priority warning once

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
Looks like it's time for end of May release.
> Release 3.7.0

- CHANGELOG.md
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
> Release jupyter-lsp v1.3

- binder/environment.yml
Fixes #616
Replaces pyls plugins with pylsp plugins where available.
None
None
> Fix binder situation

- codeql-analysis.yml
This can sometimes help to find some code smells, and it is already used in JupyterLab.
> Add CodeQL

- python_packages/jupyter_lsp/jupyter_lsp/specs/texlab.py
Closes #701
Adds troubleshooting for texlab
TBD
None
> Document texlab troubleshooting

- .gitignore
- README.md
This PR completes updates which were never merged from PR: #126.
None
None
None
> Clarify restart of JupyterLab after install

- packages/jupyterlab-lsp/src/components/statusbar.tsx
Follow-up of https://github.com/jupyter-lsp/jupyterlab-lsp/pull/700 due to bug encounter when generating the POT file (see that [issue](https://github.com/jupyterlab/language-packs/issues/198))
Add fake context for string converted to plural but without changing their id to create a new unique distinct reference for them.
N/A
N/A
> Fix identifier for pluralized strings

- .github/ISSUE_TEMPLATE/bug_report.md
Request language server info in bug report template
> Request language server info in bug report template

- .github/workflows/job.test.yml
Minor change to the CI config so that it runs on 3.x branch
> Run CI on 3.x

- binder/environment.yml
Workaround for https://github.com/jupyterhub/repo2docker/issues/1140
> Add r-base version to fix Binder

- package.json
- yarn.lock
> Pin node-gyp so that CI passes on Windows

- package.json
- yarn.lock
> Backport PR #771 on branch 3.x (Pin node-gyp so that CI passes on Windows)

- atest/03_Notebook.robot
- atest/05_Features/Completion.robot
- atest/07_Configuration.robot
- atest/Keywords.robot
- binder/overrides.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/texlab.schema.json
- scripts/atest.py
Backport PR https://github.com/jupyter-lsp/jupyterlab-lsp/pull/770 on branch 3.x (Fix tests for JupyterLab 3.3)
> Backport PR #770 on branch 3.x (Fix tests for JupyterLab 3.3)

- packages/metapackage/package.json
- requirements/github-actions.yml
- yarn.lock
Bakcport of dependenceis version bumps and pytest-flake8 pin.
> Backport PRs #781 and #761 on branch 3.x 

- atest/00_Smoke.robot
- atest/01_Editor.robot
- atest/02_Settings.robot
- atest/03_Notebook.robot
- atest/04_Interface/BackendFailure.robot
- atest/04_Interface/DiagnosticsPanel.robot
- atest/04_Interface/Statusbar.robot
- atest/05_Features/Completion.robot
- atest/05_Features/Diagnostics.robot
- atest/05_Features/Highlights.robot
- atest/05_Features/Hover.robot
- atest/05_Features/Jump.robot
- atest/05_Features/Signature.robot
- atest/05_Features/Syntax_highlighting.robot
- atest/06_Style.robot
- atest/07_Configuration.robot
- atest/Keywords.resource
- atest/Variables.resource
- docs/rtd.yml
- python_packages/jupyter_lsp/jupyter_lsp/handlers.py
- python_packages/jupyter_lsp/jupyter_lsp/manager.py
- python_packages/jupyter_lsp/jupyter_lsp/stdio.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/conftest.py
- python_packages/jupyter_lsp/jupyter_lsp/types.py
> Fix CI regressions, make tests work with JupyterLab 3.4

- atest/05_Features/Completion.robot
- atest/07_Configuration.robot
- atest/Keywords.resource
- atest/Variables.resource
> Fix CI failures with Python 3.10

- packages/jupyterlab-lsp/src/connection_manager.ts
fixes #819 
Fixed web socket url
Used ServerConnection service to get valid web socket url
> Fix web socket url

- docs/Language Servers.ipynb
- docs/Third Party Language Servers.md
Adding a markdown file for third party lsp as suggested in https://github.com/jupyter-lsp/jupyterlab-lsp/issues/824
> Create Third Party Language Servers.md

- package.json
- yarn.lock
> Upgrade lerna to v5.1.x

- atest/05_Features/Completion.robot
- atest/07_Configuration.robot
- atest/Keywords.robot
- atest/Variables.robot
- docs/rtd.yml
- python_packages/jupyter_lsp/jupyter_lsp/handlers.py
- python_packages/jupyter_lsp/jupyter_lsp/manager.py
- python_packages/jupyter_lsp/jupyter_lsp/stdio.py
- python_packages/jupyter_lsp/jupyter_lsp/tests/conftest.py
- python_packages/jupyter_lsp/jupyter_lsp/types.py
Backport PR #809: Fix CI regressions, make tests work with JupyterLab 3.4.
Also backports CI fixes from #813 and ce2c11094751562d1928744738a6038c3b7b1c53.
> Backport PR #809: Fix CI, make tests work with JupyterLab 3.4

- CHANGELOG.md
- packages/completion-theme/src/index.ts
- packages/completion-theme/style/index.css
- packages/jupyterlab-lsp/src/features/completion/completion.ts
Backport PR https://github.com/jupyter-lsp/jupyterlab-lsp/pull/829 on branch 3.x (Completion/cleanup when disabled)
> Backport PR #829 on branch 3.x (Completion/cleanup when disabled)

- CHANGELOG.md
- packages/completion-theme/package.json
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Prepare jupyterlab-lsp 3.10.2 release

- packages/jupyterlab-lsp/src/editor_integration/codemirror.ts
- packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
- packages/jupyterlab-lsp/src/features/highlights.ts
> Backport PR #847: Improve performance of diagnostics and highlights

- binder/postBuild
> Fix an OpenSSL-related error in building the Binder image

- atest/05_Features/Completion.robot
- atest/05_Features/Signature.robot
- atest/Variables.resource
- docs/Installation.ipynb
- packages/jupyterlab-lsp/src/features/completion/completion.ts
> Fix more flaky completion tests

- packages/jupyterlab-lsp/src/features/hover.ts
Fixes https://github.com/jupyter-lsp/jupyterlab-lsp/issues/859
* Input and output types of the function `on_hover` 
* Technically, the change in `on_hover` argument is unnecessary; it was to clarify the `Throttler`'s behavior.
* Process hover only when the virtual positions of a query and a response match
None.
None.
> Fix sporadic misplacement of hover tooltips

- atest/04_Interface/BackendFailure.robot
- atest/05_Features/Jump.robot
- atest/Keywords.resource
- atest/Variables.resource
- atest/__init__.robot
An attempt to speed up tests. Promising results locally (1/3rd off).
> Speed up tests by not reloading page within suites

- CHANGELOG.md
Releasing tomorrow
Edit: will get #867 in first
> Add release dates in CHANGELOG.md

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
Planning to release on Monday (evening UTC).
> Prepare v4.1.0 release

- atest/01_Editor.robot
- atest/03_Notebook.robot
- atest/examples/Foreign extractors.ipynb
- package.json
- packages/jupyterlab-lsp/schema/plugin.json
- python_packages/jupyter_lsp/jupyter_lsp/specs/bash_language_server.py
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/README.md
- python_packages/jupyter_lsp/jupyter_lsp/specs/config/bash-language-server.schema.json
- requirements/github-actions.yml
- yarn.lock
Fixes #937
Correct the path to the CLI script file.
> Installed bash_language_server not detected / not usable

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
Lets get beta out for testing.
> Bump version to 5.0.0-beta.0

- .github/workflows/job.test.yml
- requirements/github-actions.yml
Noticed in #980 
Adds `4.x`
None
None
> Run CI on 4.x branch PRs

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
> Bump version to 4.3, update changelog

- CHANGELOG.md
> Forward-port changelog for 4.3 release

- packages/jupyterlab-lsp/schema/diagnostics.json
None
Fix typo in setting title
Correct word in setting title
None
> Fix typo in setting title

- CHANGELOG.md
- packages/completion-theme/package.json
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
- yarn.lock
A number of bug fixes in these two!
> Prepare jupyterlab-lsp 5.0.1 and jupyter-lsp 2.2.1 releases

- python_packages/jupyter_lsp/jupyter_lsp/__init__.py
> Address warning about renamed extension_points

- CHANGELOG.md
More info on changes in jupyter-lsp 2.2.2
> Update `CHANGELOG.md` with additional info on jupyter-lsp release

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
This is a tiny patch release with two bug fixes.
> Prepare 5.0.3 release

- .github/workflows/job.test.yml
- packages/code-jumpers/package.json
- packages/completion-theme/package.json
- packages/jupyterlab-lsp/package.json
- packages/jupyterlab-lsp/src/adapters/fileeditor.ts
- yarn.lock
Follow-up to https://github.com/jupyter-lsp/jupyterlab-lsp/pull/1061 - the two packages also needs bumping for npm upload
> Minor version/debug statement cleanup in preparation for v5.1

- CHANGELOG.md
- packages/jupyterlab-lsp/package.json
- packages/metapackage/package.json
- python_packages/jupyter_lsp/jupyter_lsp/_version.py
Prepare 5.2.0 release and jupyter-lsp 2.2.6
> Prepare 5.2.0 release and jupyter-lsp 2.2.6
